// Per-app traffic in About → Link.
//
// The link panel's class table says HOW the link is being used; this says
// by WHOM. The interesting property is not that a table renders — it is
// that traffic generated by one named app is attributed to that app and
// not to another, and that the rows reconcile with the class totals they
// were derived from.
//
// Both halves: the terminal really streams bytes over a raw channel (the
// BE side of the accounting) and the panel really names it (the FE side).

import { test, expect } from '../fixtures/router';

test.describe('about: per-app traffic', () => {
  test('bytes a terminal streams are attributed to the terminal', async ({ page, router }) => {
    await page.goto(router.url);
    await expect(page.locator('wash-app-session')).toBeVisible();

    // Generate real, attributable traffic: pty output rides a raw
    // channel bound to com.wash.term, which is exactly the seam the
    // router attributes from.
    const launched = await router.controlRequest({ t: 'launch', app_id: 'com.wash.term' });
    expect(launched.t).toBe('launched');
    const term = page.locator('wash-app-term');
    await page.waitForSelector('wash-app-term .xterm-rows', { timeout: 10_000 });
    // xterm mounted is not the shell being ready; typing before the prompt
    // loses the first keystrokes (docs/TEST_FLAKES.md C5).
    await expect(term).toContainText(/\$|#|>/, { timeout: 10_000 });
    await term.click();
    await page.keyboard.type('seq 1 4000\n');
    await expect(term.locator('.xterm-rows')).toContainText('4000', { timeout: 20_000 });

    // Open About and read the panel.
    await page.locator('button[title="Apps"]').click();
    await page.getByRole('button', { name: /About wash/ }).click();
    const about = page.locator('wash-app-about');
    await expect(about).toBeVisible();

    const table = about.locator('[data-testid="about-app-traffic"]');
    // The stats push is ~1/s, so the first render can precede the row.
    await expect(table).toBeVisible({ timeout: 15_000 });
    const termRow = table.locator('[data-testid="about-app-traffic-row-term"]');
    await expect(termRow).toBeVisible({ timeout: 15_000 });

    // The terminal's own bytes, not somebody else's: 4000 lines is
    // comfortably over a kilobyte, and the row reports a size not a dash.
    // Polled, not read once: the row appears on the FIRST ~1/s stats push
    // that counted any terminal bytes, which on a slow runner is a few
    // hundred of them ("674 B" on CI) — the kilobytes land on the next.
    await expect(termRow).not.toContainText('— —');
    const total = termRow.locator('td').last();
    await expect(total).toHaveText(/[0-9.]+ (KB|MB)/, { timeout: 15_000 });
    // And in the right CLASS: pty output rides Bulk, so the split has to
    // land there rather than lumping an app's whole share into one number.
    // Columns are App, then the four classes, then Total.
    const cells = await termRow.locator('td').allInnerTexts();
    const [, , bulk] = cells;
    expect(bulk).toMatch(/[0-9.]+ (KB|MB)/);

    // The derived row is present and labelled as the router's, so the
    // reader can see why the app rows do not sum to the class totals.
    await expect(table.locator('[data-testid="about-app-traffic-row-router (lifecycle)"]')).toBeVisible();
  });
});
