import { fileURLToPath } from 'node:url';
import { readFileSync, writeFileSync, renameSync } from 'node:fs';
import { join } from 'node:path';
import { test, expect } from '../fixtures/router';

const FAKE_DIR=fileURLToPath(new URL('../../out/e2e',import.meta.url));
test.use({routerOpts:{apps:['session','about','agentd','agents','ai','notify'],extraEnv:{PATH:`${FAKE_DIR}:${process.env.PATH??''}`,WASH_FAKE_WORKSPACE:'1'}}});

test('MCP configures a live workspace, collaborates across idle turns, and uninstalls cleanly',async({page,router})=>{
 test.setTimeout(90_000);
 await page.goto(router.url);
 await expect(page.locator('wash-app-session')).toBeVisible();
 const started=await router.controlRequest({t:'launch',app_id:'com.wash.ai'});
 await router.controlRequest({t:'msg',instance_id:String(started.instance_id),data:{kind:'start',agent:'codex',cwd:router.xdgConfigHome,prompt:''}});
 const app=page.locator('wash-app-ai');
 const composer=app.locator('[data-testid="agent-composer"]').first();
 await expect(composer).toBeEnabled();
 await expect(app.locator('[data-testid="workspace-sidebar"]')).toHaveCount(0);
 const state=()=>JSON.parse(readFileSync(join(router.xdgStateHome,'wash/workspaces.json'),'utf8')).workspaces.at(-1);
 const tool=async(name:string,args:object={})=>{
  await composer.fill(`workspace ${name} ${JSON.stringify(args)}`);await composer.press('Enter');
 };
 await tool('setup_workspace',{name:'Redoubt test',items:[{id:'timer',text:'Build timer',state:'pending'}]});
 const sidebar=app.locator('[data-testid="workspace-sidebar"]');
 await expect(sidebar).toBeVisible();
 await tool('plan_update_item',{id:'timer',state:'active',emoji:'🔨'});
 await expect(sidebar.locator('[data-testid="workspace-item-timer"]')).toContainText('active');
 const doc=join(router.xdgConfigHome,'PLAN.md');writeFileSync(doc,'# Timer design\nFirst version.');
 await tool('document_set',{path:doc,title:'Design notes'});
 await sidebar.getByRole('button',{name:'Design notes',exact:true}).click();
 await expect(sidebar.locator('[data-testid="workspace-document"]')).toContainText('First version');
 writeFileSync(doc+'.tmp','# Timer design\nAtomic replacement.');renameSync(doc+'.tmp',doc);
 await expect(sidebar.locator('[data-testid="workspace-document"]')).toContainText('Atomic replacement');
 await tool('member_spawn',{name:'Architect',instructions:'Review clock designs.',lifetime:'resident'});
 await expect.poll(()=>state().members.length).toBe(2);
 const resident=state().members.find((m:any)=>m.name==='Architect').id;
 await expect.poll(()=>state().messages.filter((m:any)=>m.recipient===resident&&m.delivery==='acknowledged').length).toBe(1);
 await tool('message_send',{recipient:resident,type:'question',body:'Which clock?'});
 await expect.poll(()=>state().messages.some((m:any)=>m.type==='answer'&&m.body==='Fixture answer')).toBe(true);
 await tool('member_spawn',{name:'Implementer',instructions:'Implement an assigned timer.',lifetime:'ephemeral',task:'WAIT_FOR_ANSWER'});
 await expect.poll(()=>state().members.find((m:any)=>m.name==='Implementer')?.state).toBe('ended');
 expect(state().assignments[0].state).toBe('completed');
 expect(state().assignments[0].result).toBe('Completed after an inbox reply');
 const retired=state().members.find((m:any)=>m.name==='Implementer').id;
 await sidebar.locator(`[data-testid="workspace-member-${retired}"]`).click();
 await expect(sidebar.locator('[data-testid="workspace-member-detail"]')).toContainText('Archived conversation');
 await expect(sidebar.locator('[data-testid="workspace-member-detail"]')).toContainText('Completed after an inbox reply');
 expect(state().members.find((m:any)=>m.id===resident).state).toBe('available');
 await tool('member_pause',{member_id:resident});
 await expect.poll(()=>state().members.find((m:any)=>m.id===resident).state).toBe('paused');
 await tool('message_send',{recipient:resident,type:'instruction',body:'Retained while paused'});
 await expect.poll(()=>state().messages.find((m:any)=>m.body==='Retained while paused')?.delivery).toBe('queued');
 await sidebar.locator(`[data-testid="workspace-member-${resident}"]`).click();
 await expect(sidebar.locator('[data-testid="workspace-member-detail"]')).toBeVisible();
 await expect(page.locator('wash-app-ai')).toHaveCount(1);
 await sidebar.getByLabel('Message Architect').fill('Human follow-up');
 await sidebar.getByRole('button',{name:'Send message',exact:true}).click();
 await expect.poll(()=>state().messages.find((m:any)=>m.body==='Human follow-up')?.sender).toBe('human');
 await sidebar.getByRole('button',{name:'Resume member',exact:true}).click();
 await expect.poll(()=>state().messages.find((m:any)=>m.body==='Human follow-up')?.delivery).toBe('acknowledged');
 expect(state().messages.find((m:any)=>m.body==='Retained while paused').delivery).toBe('acknowledged');
 await expect(sidebar.locator('[data-testid="workspace-member-detail"]')).toContainText('Human follow-up');
 await tool('member_set_status',{text:'Review complete',emoji:'✅'});
 await expect(sidebar).toContainText('Review complete');
 await tool('decision_request',{text:'Ship the timer?'});
 await sidebar.getByLabel('Decision response').fill('Proceed');
 await sidebar.getByRole('button',{name:'Answer',exact:true}).click();
 await expect.poll(()=>state().messages.some((m:any)=>m.type==='decision_response'&&m.sender==='human')).toBe(true);
 await tool('flash_message',{text:'Timer milestone reached',emoji:'🎉'});
 await router.controlRequest({t:'launch',app_id:'com.wash.about'});
 await expect(page.locator('wash-app-about')).toBeVisible();
 const flash=page.locator('[data-testid="notification"]').filter({hasText:'Timer milestone reached'});
 await expect(flash).toBeVisible();
 const focusCursor=router.logCursor();
 await flash.click();
 await router.waitForLog(/agentd: focus key=.*raising controller=/,10_000,focusCursor);
 await tool('plan_update_item',{id:'timer',state:'done'});
 await expect(sidebar.locator('[data-testid="workspace-item-timer"]')).toContainText('done');
 await page.reload();
 await expect(sidebar).toBeVisible();
 await expect(sidebar.locator('[data-testid="workspace-item-timer"]')).toContainText('done');
 await tool('teardown_workspace');
 await expect(sidebar).toHaveCount(0);
 expect(readFileSync(doc,'utf8')).toContain('Atomic replacement');
 expect(state().state).toBe('ended');
 await tool('setup_workspace',{name:'Another project'});
 await expect(sidebar).toContainText('Another project');
 await expect(page.locator('wash-app-ai')).toHaveCount(1);
});


test('MCP reads workspace JSON and launches named profiles with model-dependent thinking', async ({ page, router }) => {
 test.setTimeout(90_000);
 await page.goto(router.url);
 await expect(page.locator('wash-app-session')).toBeVisible();
 const started = await router.controlRequest({ t: 'launch', app_id: 'com.wash.ai' });
 await router.controlRequest({ t: 'msg', instance_id: String(started.instance_id), data: { kind: 'start', agent: 'codex', cwd: router.xdgConfigHome, prompt: '' } });
 const app = page.locator('wash-app-ai');
 const composer = app.locator('[data-testid="agent-composer"]').first();
 const transcript = app.locator('[data-testid="agent-transcript"]').first();
 const outputs = transcript.getByText(/^WORKSPACE_(RESULT|ERROR) /);
 await expect(composer).toBeEnabled();
 const tool = async (name: string, args: object = {}, error = false) => {
  const count = await outputs.count();
  await composer.fill(`workspace ${name} ${JSON.stringify(args)}`);
  await composer.press('Enter');
  await expect(outputs).toHaveCount(count + 1);
  const text = await outputs.last().innerText();
  expect(text, `MCP ${name} response`).toMatch(error ? /^WORKSPACE_ERROR / : /^WORKSPACE_RESULT /);
  return error ? text : JSON.parse(text.slice('WORKSPACE_RESULT '.length));
 };
 expect(await tool('workspace_get')).toBeNull();
 await expect(app.locator('[data-testid="workspace-sidebar"]')).toHaveCount(0);
 await tool('setup_workspace', { name: 'Profiles' });
 const before = await tool('workspace_get');
 expect(before.sessions[before.workspace.orchestrator].config_options.map((c: any) => c.category)).toEqual(['model', 'thought_level']);
 await tool('workspace_configure', {
  expected_revision: before.workspace.revision,
  profiles: { god: { provider: 'codex', model: 'smart', thinking: 'high' }, pleb: { provider: 'codex', model: 'fast', thinking: 'low' } },
  default_profile: 'pleb',
 });
 const resident = await tool('member_spawn', { name: 'Architect', profile: 'god', instructions: 'Wait for design questions.', lifetime: 'resident' });
 expect(resident.profile).toBe('god');
 expect(resident.initial_configs).toEqual({ model: 'smart', reasoning_effort: 'high' });
 const sidebar = app.locator('[data-testid="workspace-sidebar"]');
 await sidebar.locator(`[data-testid="workspace-member-${resident.id}"]`).click();
 await expect(sidebar.locator('[data-testid="workspace-member-launch"]')).toHaveText('Launched: god · codex · smart · thinking high');
 await tool('workspace_configure', { profiles: { god: { provider: 'codex', model: 'fast', thinking: 'low' } } });
 const helper = await tool('member_spawn', { name: 'Helper', instructions: 'Wait for work.', lifetime: 'resident' });
 expect(helper.profile).toBe('pleb');
 expect(helper.initial_configs).toEqual({ model: 'fast', reasoning_effort: 'low' });
 const override = await tool('member_spawn', { name: 'Reviewer', profile: 'god', model: 'smart', thinking: 'high', instructions: 'Wait for a review.', lifetime: 'resident' });
 expect(override.initial_configs).toEqual({ model: 'smart', reasoning_effort: 'high' });
 await tool('member_spawn', { name: 'Unknown', profile: 'missing', instructions: 'Must not launch.', lifetime: 'resident' }, true);
 await tool('member_spawn', { name: 'Invalid thinking', profile: 'pleb', thinking: 'high', instructions: 'Must not run.', lifetime: 'resident' }, true);
 const after = await tool('workspace_get', { include_messages: true });
 expect(after.workspace.profiles.god.model).toBe('fast');
 expect(after.workspace.members.find((m: any) => m.id === resident.id).launch_settings).toMatchObject({ model: 'smart', thinking: 'high' });
 expect(after.sessions[resident.id].config_options.find((c: any) => c.id === 'model').currentValue).toBe('smart');
 expect(after.workspace.members.some((m: any) => m.name === 'Unknown')).toBe(false);
 const failed = after.workspace.members.find((m: any) => m.name === 'Invalid thinking');
 expect(failed.state).toBe('failed');
 expect(after.workspace.messages.some((m: any) => m.recipient === failed.id)).toBe(false);
 await tool('workspace_configure', { expected_revision: before.workspace.revision, name: 'Stale edit' }, true);
 await tool('workspace_configure', { profiles: { god: null }, default_profile: '' });
 const removed = await tool('workspace_get');
 expect(removed.workspace.profiles.god).toBeUndefined();
 expect(removed.workspace.profiles.pleb.model).toBe('fast');
 expect(removed.workspace.default_profile).toBe('');
 expect(removed.workspace.name).toBe('Profiles');
 await tool('teardown_workspace');
 await expect(sidebar).toHaveCount(0);
});
