import { fileURLToPath } from 'node:url';
import { readFileSync, writeFileSync, renameSync } from 'node:fs';
import { join } from 'node:path';
import { test, expect } from '../fixtures/router';
import { closeButtonOf } from '../fixtures/agents';

const FAKE_DIR=fileURLToPath(new URL('../../out/e2e',import.meta.url));
test.use({routerOpts:{apps:['session','about','agentd','agents','ai','notify'],extraEnv:{PATH:`${FAKE_DIR}:${process.env.PATH??''}`,WASH_FAKE_WORKSPACE:'1'}}});

test('MCP configures a live workspace, collaborates across idle turns, and uninstalls cleanly',async({page,router})=>{
 test.setTimeout(90_000);
 await page.goto(router.url);
 await expect(page.locator('wash-app-session')).toBeVisible();
 const started=await router.controlRequest({t:'launch',app_id:'com.wash.ai'});
 await router.controlRequest({t:'msg',instance_id:String(started.instance_id),data:{kind:'start',agent:'codex',cwd:router.xdgConfigHome,prompt:''}});
 const app=page.locator('wash-app-ai');
 const composer=app.locator('[data-testid="agent-composer"]').first();
 await expect(composer).toBeEnabled();
 await expect(app.locator('[data-testid="workspace-sidebar"]')).toHaveCount(0);
 const state=()=>JSON.parse(readFileSync(join(router.xdgStateHome,'wash/workspaces.json'),'utf8')).workspaces.at(-1);
 const tool=async(name:string,args:object={})=>{
  if (await app.getByRole('tab',{name:'Conversation',exact:true}).count()) await app.getByRole('tab',{name:'Conversation',exact:true}).click();
  await composer.fill(`workspace ${name} ${JSON.stringify(args)}`);await composer.press('Enter');
 };
 await tool('workspace_configure',{workspace:{name:'Redoubt test'},plan:{items:{timer:{text:'Build timer',state:'pending'}}}});
 const sidebar=app.locator('[data-testid="workspace-sidebar"]');
 await expect(sidebar).toBeVisible();
 await tool('workspace_configure',{plan:{items:{timer:{state:'active',emoji:'🔨'}}}});
 await sidebar.locator('[data-testid="workspace-plan-link"]').click();
 await expect(app.locator('[data-testid="workspace-item-timer"]')).toContainText('active');
 const doc=join(router.xdgConfigHome,'PLAN.md');writeFileSync(doc,'# Timer design\nFirst version.');
 await tool('workspace_configure',{document:{path:doc,title:'Design notes'}});
 await sidebar.getByRole('button',{name:'Design notes',exact:true}).click();
 await expect(app.locator('[data-testid="workspace-document"]')).toContainText('First version');
 writeFileSync(doc+'.tmp','# Timer design\nAtomic replacement.');renameSync(doc+'.tmp',doc);
 await expect(app.locator('[data-testid="workspace-document"]')).toContainText('Atomic replacement');
 await tool('workspace_configure',{members:{architect:{name:'Architect',instructions:'Review clock designs.',lifetime:'resident'}}});
 await expect.poll(()=>state().members.length).toBe(2);
 const resident=state().members.find((m:any)=>m.name==='Architect').id;
 await expect.poll(()=>state().messages.filter((m:any)=>m.recipient===resident&&m.delivery==='acknowledged').length).toBe(1);
 expect(state().members.find((m:any)=>m.id===resident).initial_configs.model).toBe('fast');
 await tool('message_send',{recipient:resident,type:'question',body:'Which clock?'});
 await expect.poll(()=>state().messages.some((m:any)=>m.type==='answer'&&m.body==='Fixture answer')).toBe(true);
 await tool('workspace_configure',{members:{implementer:{name:'Implementer',instructions:'Implement an assigned timer.',lifetime:'ephemeral',task:'WAIT_FOR_ANSWER'}}});
 await expect.poll(()=>state().members.find((m:any)=>m.name==='Implementer')?.state).toBe('ended');
 expect(state().assignments[0].state).toBe('completed');
 expect(state().assignments[0].result).toBe('Completed after an inbox reply');
 const retired=state().members.find((m:any)=>m.name==='Implementer').id;
 await expect(sidebar.locator(`[data-testid="workspace-usage-${retired}"]`)).toContainText('2,048 / 32,000 tokens');
 await sidebar.locator(`[data-testid="workspace-member-${retired}"]`).click();
 await expect(app.locator('[data-testid="workspace-member-detail"]')).toContainText('Archived conversation');
 await expect(app.locator('[data-testid="workspace-member-detail"]')).toContainText('Completed after an inbox reply');
 expect(state().members.find((m:any)=>m.id===resident).state).toBe('available');
 await tool('member_control',{action:'pause',member_ids:[resident]});
 await expect.poll(()=>state().members.find((m:any)=>m.id===resident).state).toBe('paused');
 await tool('message_send',{recipient:resident,type:'instruction',body:'Retained while paused'});
 await expect.poll(()=>state().messages.find((m:any)=>m.body==='Retained while paused')?.delivery).toBe('queued');
 await sidebar.locator(`[data-testid="workspace-member-${resident}"]`).click();
 await expect(app.locator('[data-testid="workspace-member-detail"]')).toBeVisible();
 await expect(page.locator('wash-app-ai')).toHaveCount(1);
 await app.getByLabel('Message Architect').fill('Human follow-up');
 await app.getByRole('button',{name:'Send message',exact:true}).click();
 await expect.poll(()=>state().messages.find((m:any)=>m.body==='Human follow-up')?.sender).toBe('human');
 await app.getByRole('button',{name:'Resume member',exact:true}).click();
 await expect.poll(()=>state().messages.find((m:any)=>m.body==='Human follow-up')?.delivery).toBe('acknowledged');
 expect(state().messages.find((m:any)=>m.body==='Retained while paused').delivery).toBe('acknowledged');
 await expect(app.locator('[data-testid="workspace-member-detail"]')).toContainText('Human follow-up');
 await tool('member_update',{status:'Review complete',emoji:'✅'});
 await expect(sidebar).toContainText('Review complete');
 await tool('decision_request',{text:'Ship the timer?'});
 await sidebar.getByLabel('Decision response').fill('Proceed');
 await sidebar.getByRole('button',{name:'Answer',exact:true}).click();
 await expect.poll(()=>state().messages.some((m:any)=>m.type==='decision_response'&&m.sender==='human')).toBe(true);
 await tool('flash_message',{text:'Timer milestone reached',emoji:'🎉'});
 await router.controlRequest({t:'launch',app_id:'com.wash.about'});
 await expect(page.locator('wash-app-about')).toBeVisible();
 const flash=page.locator('[data-testid="notification"]').filter({hasText:'Timer milestone reached'});
 await expect(flash).toBeVisible();
 const focusCursor=router.logCursor();
 await flash.click();
 await router.waitForLog(/agentd: focus key=.*raising controller=/,10_000,focusCursor);
 await tool('workspace_configure',{plan:{items:{timer:{state:'done'}}}});
 await sidebar.locator('[data-testid="workspace-plan-link"]').click();
 await expect(app.locator('[data-testid="workspace-item-timer"]')).toContainText('done');
 await page.reload();
 // Reload restores the About window used to check flash visibility in front.
 await closeButtonOf(page,page.locator('wash-app-about')).click();
 await expect(page.locator('wash-app-about')).toHaveCount(0);
 await expect(sidebar).toBeVisible();
 await sidebar.locator('[data-testid="workspace-plan-link"]').click();
 await expect(app.locator('[data-testid="workspace-item-timer"]')).toContainText('done');
 await tool('workspace_end');
 await expect(sidebar).toHaveCount(0);
 expect(readFileSync(doc,'utf8')).toContain('Atomic replacement');
 expect(state().state).toBe('ended');
 await tool('workspace_configure',{workspace:{name:'Another project'}});
 await expect(sidebar).toContainText('Another project');
 await expect(page.locator('wash-app-ai')).toHaveCount(1);
});


test('MCP reads workspace JSON and launches named profiles with model-dependent thinking', async ({ page, router }) => {
 test.setTimeout(90_000);
 await page.goto(router.url);
 await expect(page.locator('wash-app-session')).toBeVisible();
 const started = await router.controlRequest({ t: 'launch', app_id: 'com.wash.ai' });
 await router.controlRequest({ t: 'msg', instance_id: String(started.instance_id), data: { kind: 'start', agent: 'codex', cwd: router.xdgConfigHome, prompt: '' } });
 const app = page.locator('wash-app-ai');
 const composer = app.locator('[data-testid="agent-composer"]').first();
 const transcript = app.locator('[data-testid="agent-transcript"]').first();
 const outputs = transcript.getByText(/^WORKSPACE_(RESULT|ERROR) /);
 await expect(composer).toBeEnabled();
 const tool = async (name: string, args: object = {}, error = false) => {
  const count = await outputs.count();
  if (await app.getByRole('tab',{name:'Conversation',exact:true}).count()) await app.getByRole('tab',{name:'Conversation',exact:true}).click();
  await composer.fill(`workspace ${name} ${JSON.stringify(args)}`);
  await composer.press('Enter');
  await expect(outputs).toHaveCount(count + 1);
  const text = await outputs.last().innerText();
  expect(text, `MCP ${name} response`).toMatch(error ? /^WORKSPACE_ERROR / : /^WORKSPACE_RESULT /);
  return error ? text : JSON.parse(text.slice('WORKSPACE_RESULT '.length));
 };
 const about = await tool('workspace_get', {view:'about'});
 expect(about.server).toBe('wash_workspace');
 expect(about.caller.role).toBe('unattached');
 expect(about.instructions).toContain('END YOUR TURN');
 expect(about.capabilities.bulk_workspace_configuration).toBe(true);
 expect(about.permissions.filesystem_enforcement).toMatch(/^unknown:/);
 expect(await tool('workspace_get')).toBeNull();
 await expect(app.locator('[data-testid="workspace-sidebar"]')).toHaveCount(0);
 await tool('workspace_configure', { workspace:{name: 'Profiles'} });
 expect((await tool('workspace_get', {view:'about'})).caller.role).toBe('orchestrator');
 const before = await tool('workspace_get');
 expect(before.sessions[before.workspace.orchestrator].config_options.map((c: any) => c.category)).toEqual(['model', 'thought_level']);
 await tool('workspace_configure', {
  expected_revision: before.workspace.revision,
  profiles: { god: { provider: 'codex', model: 'smart', thinking: 'high' }, pleb: { provider: 'codex', model: 'fast', thinking: 'low' } },
  default_profile: 'pleb',
 });
 const resident = (await tool('workspace_configure', {members:{architect:{ name: 'Architect', profile: 'god', instructions: 'Wait for design questions.', lifetime: 'resident' }}})).launches.architect;
 expect(resident.profile).toBe('god');
 expect(resident.initial_configs).toEqual({ model: 'smart', reasoning_effort: 'high' });
 const sidebar = app.locator('[data-testid="workspace-sidebar"]');
 await sidebar.locator(`[data-testid="workspace-member-${resident.id}"]`).click();
 await expect(app.locator('[data-testid="workspace-member-launch"]')).toHaveText('Launched: god · codex · smart · thinking high');
 await tool('workspace_configure', { profiles: { god: { provider: 'codex', model: 'fast', thinking: 'low' } } });
 const helper = (await tool('workspace_configure', {members:{helper:{ name: 'Helper', instructions: 'Wait for work.', lifetime: 'resident' }}})).launches.helper;
 expect(helper.profile).toBe('pleb');
 expect(helper.initial_configs).toEqual({ model: 'fast', reasoning_effort: 'low' });
 const override = (await tool('workspace_configure', {members:{reviewer:{ name: 'Reviewer', profile: 'god', model: 'smart', thinking: 'high', instructions: 'Wait for a review.', lifetime: 'resident' }}})).launches.reviewer;
 expect(override.initial_configs).toEqual({ model: 'smart', reasoning_effort: 'high' });
 await tool('workspace_configure', {members:{unknown:{ name: 'Unknown', profile: 'missing', instructions: 'Must not launch.', lifetime: 'resident' }}}, true);
 const failedLaunch = await tool('workspace_configure', {members:{invalid:{ name: 'Invalid thinking', profile: 'pleb', thinking: 'high', instructions: 'Must not run.', lifetime: 'resident' }}});
 expect(failedLaunch.launches.invalid.state).toBe('failed');
 expect(failedLaunch.launches.invalid.error).toBeTruthy();
 const after = await tool('workspace_get', { include_messages: true });
 expect(after.workspace.profiles.god.model).toBe('fast');
 expect(after.workspace.members.find((m: any) => m.id === resident.id).launch_settings).toMatchObject({ model: 'smart', thinking: 'high' });
 expect(after.sessions[resident.id].config_options.find((c: any) => c.id === 'model').currentValue).toBe('smart');
 expect(after.workspace.members.some((m: any) => m.name === 'Unknown')).toBe(false);
 const failed = after.workspace.members.find((m: any) => m.name === 'Invalid thinking');
 expect(failed.state).toBe('failed');
 expect(after.workspace.messages.some((m: any) => m.recipient === failed.id)).toBe(false);
 await tool('workspace_configure', { expected_revision: before.workspace.revision, name: 'Stale edit' }, true);
 await tool('workspace_configure', { profiles: { god: null }, default_profile: '' });
 const removed = await tool('workspace_get');
 expect(removed.workspace.profiles.god).toBeUndefined();
 expect(removed.workspace.profiles.pleb.model).toBe('fast');
 expect(removed.workspace.default_profile).toBe('');
 expect(removed.workspace.name).toBe('Profiles');
 await tool('workspace_end');
 await expect(sidebar).toHaveCount(0);
});


test('sidebar shows live context and activity, and human messages remain distinct', async ({page,router}) => {
 test.setTimeout(45_000);
 await page.goto(router.url);
 await expect(page.locator('wash-app-session')).toBeVisible();
 const started=await router.controlRequest({t:'launch',app_id:'com.wash.ai'});
 await router.controlRequest({t:'msg',instance_id:String(started.instance_id),data:{kind:'start',agent:'codex',cwd:router.xdgConfigHome,prompt:''}});
 const app=page.locator('wash-app-ai');
 const composer=app.locator('[data-testid="agent-composer"]').first();
 await expect(composer).toBeEnabled();
 await composer.fill('workspace workspace_configure {"workspace":{"name":"Telemetry"}}');
 await composer.press('Enter');
 const sidebar=app.locator('[data-testid="workspace-sidebar"]');
 await expect(sidebar).toBeVisible();
 const state=()=>JSON.parse(readFileSync(join(router.xdgStateHome,'wash/workspaces.json'),'utf8')).workspaces.at(-1);
 const lead=state().orchestrator;
 const dot=sidebar.locator(`[data-testid="workspace-activity-${lead}"]`);
 await expect(dot).toHaveAttribute('data-activity','idle');
 await composer.fill('workspace_activity');await composer.press('Enter');
 await expect(dot).toHaveAttribute('data-activity','thinking');
 await expect(sidebar.locator(`[data-testid="workspace-usage-${lead}"]`)).toContainText('14,689 / 258,400 tokens');
 await expect(dot).toHaveCSS('animation-name','wash-workspace-pulse');
 await page.emulateMedia({reducedMotion:'reduce'});
 await expect(dot).toHaveCSS('animation-name','none');
 await expect(dot).toHaveAttribute('data-activity','tool');
 await expect(sidebar).toContainText('Running test suite');
 await expect(dot).toHaveAttribute('data-activity','responding');
 await expect(dot).toHaveAttribute('data-activity','idle');
 await expect.poll(()=>state().members[0].usage?.used).toBe(14689);
 const human=app.locator('[data-testid="agent-human-message"]').last();
 await expect(human).toHaveText('workspace_activity');
 await expect(human).toHaveCSS('font-weight','600');
 const colors=await human.evaluate(el=>({fg:getComputedStyle(el).color,bg:getComputedStyle(el).backgroundColor}));
 expect(colors.bg).not.toBe('rgba(0, 0, 0, 0)');
 await page.screenshot({path:test.info().outputPath('workspace-activity.png')});
 await composer.fill('workspace member_update {"waiting":{"reason":"Awaiting next instruction"}}');await composer.press('Enter');
 await expect(dot).toHaveAttribute('data-activity','waiting-message');
 await expect(dot).toHaveAttribute('data-pulse','false');
 await page.reload();
 await expect(sidebar.locator(`[data-testid="workspace-usage-${lead}"]`)).toContainText('2,048 / 32,000 tokens');
});


test('workspace tabs preserve drafts and the sidebar resizes without overflowing', async ({page,router}) => {
 test.setTimeout(60_000);
 await page.goto(router.url);
 await expect(page.locator('wash-app-session')).toBeVisible();
 const started=await router.controlRequest({t:'launch',app_id:'com.wash.ai'});
 await router.controlRequest({t:'msg',instance_id:String(started.instance_id),data:{kind:'start',agent:'codex',cwd:router.xdgConfigHome,prompt:''}});
 const app=page.locator('wash-app-ai');
 const main=app.getByTestId('workspace-main');
 const sidebar=app.getByTestId('workspace-sidebar');
 const composer=app.getByTestId('agent-composer');
 const outputs=main.getByText(/^WORKSPACE_RESULT /);
 const tool=async(name:string,args:object={})=>{
  const conversation=app.getByRole('tab',{name:'Conversation',exact:true});
  if(await conversation.count()) await conversation.click();
  const count=await outputs.count();
  await composer.fill(`workspace ${name} ${JSON.stringify(args)}`);await composer.press('Enter');
  await expect(outputs).toHaveCount(count+1);
  return JSON.parse((await outputs.last().innerText()).slice('WORKSPACE_RESULT '.length));
 };
 await expect(composer).toBeEnabled();
 await tool('workspace_configure',{workspace:{name:'Tab navigation'},plan:{items:{clock:{text:'Verify timer clock',state:'active'}}}});
 const member=(await tool('workspace_configure',{members:{architect:{name:'Architect',lifetime:'resident',instructions:'Wait for a design question.'}}})).launches.architect;
 const other=(await tool('workspace_configure',{members:{reviewer:{name:'Reviewer',lifetime:'resident',instructions:'Wait for review.'}}})).launches.reviewer;
 await composer.fill('Keep this conversation draft');
 await sidebar.getByTestId('workspace-plan-link').click();
 await expect(main.getByTestId('workspace-item-clock')).toContainText('Verify timer clock');
 await expect(sidebar.getByTestId('workspace-item-clock')).toHaveCount(0);
 await sidebar.getByTestId(`workspace-member-${member.id}`).click();
 await expect(main.getByTestId('workspace-member-detail')).toBeVisible();
 await expect(sidebar.getByTestId('workspace-member-detail')).toHaveCount(0);
 await app.getByLabel('Message Architect').fill('Keep this architect draft');
 await sidebar.getByTestId(`workspace-member-${other.id}`).click();
 await app.getByLabel('Message Reviewer').fill('Keep this reviewer draft');
 await sidebar.getByTestId(`workspace-member-${member.id}`).click();
 await expect(app.getByLabel('Message Architect')).toHaveValue('Keep this architect draft');
 await sidebar.getByTestId(`workspace-member-${member.id}`).click();
 await expect(app.getByRole('tab',{name:/Architect/})).toHaveCount(1);
 await app.getByRole('tab',{name:'Conversation',exact:true}).click();
 await expect(composer).toHaveValue('Keep this conversation draft');
 await app.getByRole('tab',{name:/Reviewer/}).click();
 await expect(app.getByLabel('Message Reviewer')).toHaveValue('Keep this reviewer draft');
 const divider=app.getByRole('separator',{name:'Resize workspace sidebar'});
 const initial=(await sidebar.boundingBox())!;
 const grip=(await divider.boundingBox())!;
 await page.mouse.move(grip.x+grip.width/2,grip.y+30);await page.mouse.down();
 await page.mouse.move(grip.x-90,grip.y+30,{steps:8});await page.mouse.up();
 await expect.poll(async()=>(await sidebar.boundingBox())!.width).toBeGreaterThan(initial.width+60);
 await divider.focus();await divider.press('ArrowRight');
 const saved=await divider.getAttribute('aria-valuenow');
 await expect.poll(async()=>app.getByTestId('workspace-layout').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);
 await page.screenshot({path:test.info().outputPath('workspace-tabs.png')});
 await app.getByRole('tab',{name:/Reviewer/}).press('Delete');
 await expect(app.getByRole('tab',{name:/Reviewer/})).toHaveCount(0);
 await expect(app.getByRole('tab',{name:/Architect/})).toBeFocused();
 await app.getByRole('tab',{name:/Architect/}).press('Home');
 await expect(composer).toHaveValue('Keep this conversation draft');
 await page.reload();
 await expect(divider).toHaveAttribute('aria-valuenow',saved!);
 await expect(app.getByRole('tab')).toHaveCount(1);
 await tool('workspace_end');
 await expect(sidebar).toHaveCount(0);
 await expect(app.getByRole('tablist',{name:'Workspace views'})).toHaveCount(0);
 await expect(composer).toBeEnabled();
 await expect(page.locator('wash-app-ai')).toHaveCount(1);
});


test('bulk workspace setup keeps package workers resident and QA survives refresh with owner attribution', async ({page,router}) => {
 test.setTimeout(90_000);
 await page.goto(router.url);await expect(page.locator('wash-app-session')).toBeVisible();
 const started=await router.controlRequest({t:'launch',app_id:'com.wash.ai'});
 await router.controlRequest({t:'msg',instance_id:String(started.instance_id),data:{kind:'start',agent:'codex',cwd:router.xdgConfigHome,prompt:''}});
 const app=page.locator('wash-app-ai'),sidebar=app.getByTestId('workspace-sidebar');
 const composer=app.getByTestId('agent-composer').first(),outputs=app.getByTestId('agent-transcript').first().getByText(/^WORKSPACE_(RESULT|ERROR) /);
 const tool=async(name:string,args:object={},error=false)=>{
  const tab=app.getByRole('tab',{name:'Conversation',exact:true});if(await tab.count())await tab.click();
  const count=await outputs.count();await composer.fill(`workspace ${name} ${JSON.stringify(args)}`);await composer.press('Enter');await expect(outputs).toHaveCount(count+1);
  const text=await outputs.last().innerText();expect(text).toMatch(error?/^WORKSPACE_ERROR /:/^WORKSPACE_RESULT /);return error?text:JSON.parse(text.slice('WORKSPACE_RESULT '.length));
 };
 await expect(composer).toBeEnabled();
 const about=await tool('workspace_get',{view:'about'});expect(about.tools).toHaveLength(12);
 expect(about.tools).not.toContain('member_spawn');
 await tool('member_spawn',{},true);
 await tool('setup_workspace',{name:'Removed'},true);
 await expect(sidebar).toHaveCount(0);
expect(about.caller.config_options.length).toBeGreaterThan(0);
 const qaPath=join(router.xdgConfigHome,'QA.md');
 const config={qa_document:{path:qaPath,title:'Package questions'},request_id:'package-setup',workspace:{name:'Package QA'},profiles:{worker:{provider:'codex',model:'fast',thinking:'low'}},members:{
  implementer:{name:'K5 implementer',profile:'worker',lifetime:'resident',package:'K5',role:'implementer',instructions:'Implement only the assigned package.',task:'First delivery'},
  red:{name:'K5 red',profile:'worker',lifetime:'resident',package:'K5',role:'reviewer',instructions:'Review defensively; wait for work.'},
 },plan:{items:{K5:{text:'K5 package',state:'active'}}}};
 await tool('workspace_configure',{...config,preview:true});await expect(sidebar).toHaveCount(0);
 const configured=await tool('workspace_configure',config);
 expect(readFileSync(qaPath,'utf8')).toContain('# Package questions');
 expect(configured.qa_document_status.state).toBe('saved');
 expect(configured.launches.implementer.state).toBe('available');expect(configured.launches.red.state).toBe('available');
 const state=()=>JSON.parse(readFileSync(join(router.xdgStateHome,'wash/workspaces.json'),'utf8')).workspaces.at(-1);
 await expect.poll(()=>state().assignments[0]?.state).toBe('completed');
 expect(state().members.find((m:any)=>m.key==='implementer').state).toBe('available');
 const repeated=await tool('workspace_configure',config);expect(repeated.receipt.members).toEqual(configured.receipt.members);expect(state().members).toHaveLength(3);
 await tool('assignment_update',{request_id:'fix-pass',updates:[{action:'create',member_id:'implementer',text:'Follow-up fix'}]});
 await expect.poll(()=>state().assignments[1]?.state).toBe('completed');expect(state().members).toHaveLength(3);
 await tool('message_send',{recipient:'red',type:'instruction',body:'ASK_PERMISSION'});
 await sidebar.getByTestId(`workspace-member-${configured.receipt.members.red}`).click();
 await expect(app.getByTestId('workspace-member-detail').getByRole('button',{name:/^Allow(\s|$)/})).toBeVisible();
 await app.getByTestId('workspace-member-detail').getByRole('button',{name:/^Allow(\s|$)/}).click();
 await expect(app.getByTestId('workspace-member-detail')).toContainText('Permission outcome: allow');
 await tool('message_send',{request_id:'open-qa',recipient:'red',type:'question',body:'Does the clock meet the bound?',qa:{id:'K5-bound',action:'open',package:'K5',title:'Wakeup bound',blocking:true}});
 await sidebar.getByTestId('workspace-question-K5-bound').click();
 await expect(app.getByTestId('workspace-qa')).toContainText('Does the clock meet the bound?');
 await expect(app.getByTestId('workspace-qa-path')).toHaveText(qaPath);
 expect(readFileSync(qaPath,'utf8')).toContain('Does the clock meet the bound?');
 await expect.poll(()=>state().qa[0].events.some((e:any)=>e.author===configured.receipt.members.red&&e.body==='Fixture answer')).toBe(true);
 await tool('decision_request',{text:'Choose the bound: recommend A, alternative B.',thread_id:'K5-bound',request_id:'owner-choice'});
 await sidebar.getByLabel('Decision response').fill('Use bound A');await sidebar.getByRole('button',{name:'Answer',exact:true}).click();
 await expect.poll(()=>state().qa[0].events.some((e:any)=>e.author==='human'&&e.body==='Use bound A')).toBe(true);
 await expect.poll(()=>readFileSync(qaPath,'utf8')).toContain('Use bound A');
 await page.reload();await expect(sidebar).toBeVisible();await sidebar.getByTestId('workspace-qa-link').click();
 await expect(app.getByTestId('workspace-qa')).toContainText('Use bound A');await expect(app.getByTestId('workspace-qa')).toContainText('Owner');
 const qa=await tool('workspace_get',{view:'qa',thread_id:'K5-bound'});
 await tool('member_update',{qa_updates:[{id:'K5-bound',action:'resolve',expected_revision:qa.thread.revision-1,evidence:'stale'}]},true);
 await tool('member_update',{request_id:'resolve-qa',status:'Package accepted',qa_updates:[{id:'K5-bound',action:'resolve',expected_revision:qa.thread.revision,evidence:'Regression tests passed; review complete.'}]});
 await expect(sidebar.getByTestId('workspace-qa-link')).toContainText('0 open');
 await tool('member_control',{action:'end',package:'K5'});
 await expect.poll(()=>state().members.filter((m:any)=>m.package==='K5').every((m:any)=>m.state==='ended')).toBe(true);
 expect(state().qa[0].state).toBe('resolved');
 expect(readFileSync(qaPath,'utf8')).toContain('Status: **resolved**');
 await sidebar.getByTestId('workspace-qa-link').click();await page.screenshot({path:test.info().outputPath('workspace-qa.png')});
 await tool('workspace_end');await expect(sidebar).toHaveCount(0);
});
