package uigen

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/sirmick/wash/internal/washnet/model"
)

// EmitTS generates TypeScript type definitions for the model: one interface per
// object and per union variant, a union alias per discriminator interface, and
// the Config interface. Field names match Go's default JSON marshalling
// (PascalCase). The wire discriminator for unions is carried by the descriptor
// (see BuildDescriptor); it is added to the JSON encoding in Phase B.
func EmitTS() string {
	var b strings.Builder
	b.WriteString("// Code generated by washnet/uigen. DO NOT EDIT.\n\n")

	// Union aliases, in first-encounter order; collect variant types to emit.
	var unionIfaces []reflect.Type
	seenIface := map[reflect.Type]bool{}
	variantTypes := map[string]reflect.Type{}
	collectUnions := func(t reflect.Type) {
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			_, flags := splitTag(f.Tag.Get("uci"))
			if has(flags, "union") && !seenIface[f.Type] {
				seenIface[f.Type] = true
				unionIfaces = append(unionIfaces, f.Type)
			}
		}
	}
	objTypes := model.ObjectTypes()
	for _, t := range objTypes {
		collectUnions(t)
	}
	for _, iface := range unionIfaces {
		variants := model.VariantsOf(iface)
		names := make([]string, len(variants))
		for i, vt := range variants {
			names[i] = vt.Name()
			variantTypes[vt.Name()] = vt
		}
		fmt.Fprintf(&b, "export type %s = %s;\n", iface.Name(), strings.Join(names, " | "))
	}
	b.WriteByte('\n')

	// Variant interfaces (sorted by name for determinism).
	var vnames []string
	for n := range variantTypes {
		vnames = append(vnames, n)
	}
	sort.Strings(vnames)
	for _, n := range vnames {
		emitInterface(&b, variantTypes[n])
	}

	// Object interfaces, in Config order.
	for _, t := range objTypes {
		emitInterface(&b, t)
	}

	// Config.
	b.WriteString("export interface Config {\n")
	ct := reflect.TypeOf(model.Config{})
	for i := 0; i < ct.NumField(); i++ {
		f := ct.Field(i)
		if f.Type.Kind() != reflect.Slice {
			continue
		}
		fmt.Fprintf(&b, "  %s?: %s[];\n", f.Name, f.Type.Elem().Name())
	}
	b.WriteString("}\n")
	return b.String()
}

func emitInterface(b *strings.Builder, t reflect.Type) {
	fmt.Fprintf(b, "export interface %s {\n", t.Name())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		uciTag := f.Tag.Get("uci")
		if uciTag == "" || uciTag == "-" {
			continue
		}
		_, flags := splitTag(uciTag)
		fmt.Fprintf(b, "  %s?: %s;\n", f.Name, tsType(f.Type, has(flags, "union")))
	}
	b.WriteString("}\n\n")
}

func tsType(ft reflect.Type, isUnion bool) string {
	if isUnion {
		return ft.Name()
	}
	switch ft {
	case addrType, prefixType:
		return "string"
	}
	switch ft.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.String:
		return "string"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "number"
	case reflect.Slice:
		return tsType(ft.Elem(), false) + "[]"
	}
	return "string"
}

// EmitI18n returns the default English label scaffold, keyed by "<GoType>.<Field>".
// Humans edit this; it is regenerated additively.
func EmitI18n() map[string]string {
	out := map[string]string{}
	var walk func(d Descriptor)
	add := func(fs []FieldDescriptor) {
		for _, f := range fs {
			out[f.LabelKey] = humanize(f.Name)
			if f.Union != nil {
				for _, v := range f.Union.Variants {
					for _, vf := range v.Fields {
						out[vf.LabelKey] = humanize(vf.Name)
					}
				}
			}
		}
	}
	walk = func(d Descriptor) {
		for _, o := range d.Objects {
			add(o.Fields)
		}
	}
	walk(BuildDescriptor())
	return out
}

// humanize splits a CamelCase identifier into spaced words (best-effort; the
// scaffold is meant to be hand-edited).
func humanize(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' && !(s[i-1] >= 'A' && s[i-1] <= 'Z') {
			b.WriteByte(' ')
		}
		b.WriteRune(r)
	}
	return b.String()
}
