package workspacemcp

// leadOnly tools always fail for a launched member (the store refuses them), so
// a member's tool list leaves their schemas out of every turn's prompt.
var leadOnly = map[string]bool{"workspace_configure": true, "workspace_end": true, "message_retry": true, "member_control": true, "plan_accept": true}

// MemberTools is Tools without the orchestrator-only operations.
func MemberTools() []Tool {
	var out []Tool
	for _, t := range Tools() {
		if !leadOnly[t.Name] {
			out = append(out, t)
		}
	}
	return out
}

func Tools() []Tool {
	str := field("string")
	boolean := field("boolean")
	integer := field("integer")
	strings := map[string]any{"type": "array", "items": str, "maxItems": 100}
	array := func(items any) any { return map[string]any{"type": "array", "items": items, "maxItems": 100} }
	enum := func(values ...string) any { return map[string]any{"type": "string", "enum": values} }
	configs := map[string]any{"type": "object", "additionalProperties": str}
	nullable := func(s any) any { return map[string]any{"anyOf": []any{s, field("null")}} }
	qa := schema(map[string]any{"id": str, "action": enum("open", "reply", "assign", "block", "resolve", "reopen"), "node": str, "title": str, "assignee": str, "body": str, "blocking": boolean, "expected_revision": integer, "decision_refs": strings, "evidence": str, "on_behalf_of": str}, "id", "action")
	// A message's qa only opens a thread, and the thread's body is the message's.
	open := schema(map[string]any{"id": str, "action": enum("open"), "node": str, "title": str, "assignee": str, "blocking": boolean, "decision_refs": strings, "on_behalf_of": str}, "id", "action")
	msgProps := map[string]any{"recipient": str, "type": enum("instruction", "question", "answer", "progress"), "body": str, "reply_to": str, "assignment_id": str, "request_id": str, "thread_id": str, "qa": open, "priority": enum("checkpoint")}
	msg := schema(msgProps, "recipient", "type", "body")
	assignment := schema(map[string]any{"action": enum("create", "complete", "fail"), "id": str, "member_id": str, "node": str, "override": str, "text": str, "body": str, "request_id": str, "cc": strings}, "action")
	// member_update reports results; it never creates an assignment.
	result := schema(map[string]any{"action": enum("complete", "fail"), "id": str, "body": str, "cc": strings}, "action", "id", "body")
	member := schema(map[string]any{"name": str, "catalog": str, "capability": enum("reviewer"), "enforcement": enum("advisory", "adapter"), "approval": enum("ask", "auto"), "provider": str, "model": str, "effort": str, "configs": configs, "subagents": enum("allow", "deny"), "cwd": str, "instructions": str, "lifetime": enum("resident", "ephemeral"), "task": str, "override": str, "can_spawn": boolean, "node": str, "role": enum("architect", "implementer", "reviewer"), "handoff_from": str, "handoff_file": str}, "name", "instructions", "lifetime")
	node := schema(map[string]any{"title": str, "emoji": str, "template": enum("milestone", "package", "step", "note"), "parent": str, "needs": strings, "body": str, "state": str, "expected_revision": integer})
	gate := schema(map[string]any{"command": str, "exit_code": integer}, "command", "exit_code")
	option := schema(map[string]any{"label": str, "description": str}, "label")
	question := schema(map[string]any{"id": str, "header": str, "question": str, "options": array(option), "multi": boolean, "recommended": str}, "question")
	messageInput := map[string]any{"messages": array(msg), "request_id": str}
	// One message and a batch share the same tool.
	for k, v := range msgProps {
		messageInput[k] = v
	}
	return []Tool{
		{"workspace_get", "Read the workspace. Default view=team: per member state, activity, status, context usage, open assignments, undelivered mail and settings. view=state: full JSON with configuration, plan, assignments, pending decisions and each live session's config_options; include_messages with after/limit pages history. view=qa: the thread index (id, node, title, state, assignee, revision); node filters; thread_id pages a thread's events (after, limit 1–100). view=about: operating guide, usable before setup. Read-only.", schema(map[string]any{"view": enum("state", "about", "qa", "team"), "include_messages": boolean, "after": str, "limit": integer, "thread_id": str, "node": str})},
		{"workspace_configure", "Orchestrator: create (workspace.name; project_root defaults to your cwd) or atomically patch the workspace; omitted fields stay, null deletes. from loads a workspace file such as \".wash/workspace.toml\"; fields in the call win. members are keyed launch definitions, each on a plan node (plan_set it first) or on the team; a member's task is its first assignment, and override:\"<reason>\" lets it start before the node's needs are done (recorded once on the node). A member's model is a slot of the catalog (frontier|coding|small) or a model id; one the adapter does not offer runs on its default, recorded. capability:\"reviewer\" makes a member read/search only (Wash's host guards everywhere; the adapter's own allowlist where it has one); subagents:\"deny\" removes its own subagent tool where the adapter can. Both and the model are advisory: the member launches, the receipt's advisories say what this provider will not enforce, and the member's applied records what held. enforcement:\"adapter\" on a reviewer refuses instead unless the adapter enforces it at a verified version. A key whose launch failed takes the changed fields alone. Also qa_dir, plan_file, legend, roles, context_warn, supervisor and catalog: view=about reference explains each. preview:true validates only; expected_revision guards. The configuration commits before launches: check each launch outcome.", schema(map[string]any{"workspace": schema(map[string]any{"name": str, "project_root": str}, "name"), "name": str, "max_active": integer, "max_members": integer, "catalog": str, "legend": str, "context_warn": field("number"), "supervisor": schema(map[string]any{"off": boolean, "quiet": str, "idle": str, "repeat": str, "max_prompts": integer}), "roles": map[string]any{"type": "object", "additionalProperties": nullable(schema(map[string]any{"instructions": str}, "instructions"))}, "from": str, "members": map[string]any{"type": "object", "additionalProperties": member}, "qa_dir": nullable(str), "plan_file": nullable(str), "expected_revision": integer, "request_id": str, "preview": boolean})},
		{"workspace_end", "Orchestrator: end the workspace's child sessions, keeping the owning conversation, files and history. Refused while plan nodes are active or reported unless confirm:true. Returns the final QA save status; failed saves keep retrying. workspace_id (full ID or a unique prefix of at least 8) ends another workspace whose orchestrator is not running in Wash, e.g. a stale one still holding a QA file.", schema(map[string]any{"workspace_id": str, "confirm": boolean})},
		{"member_control", "Orchestrator: pause, resume, interrupt or end members by ID/key, or every member on a plan node (and inside it). interrupt ends the current turn and leaves the member available (pause also stops dispatch until resumed). checkpoint is the safe stop: interrupt plus a priority instruction to save, write its handoff and set waiting, superseding your earlier queued instructions to it (body adds to it); then end it and relaunch with handoff_from. configure (orchestrator) changes a member's adapter settings, live and on every resume, e.g. configs:{mode:\"default\"} once you approve a plan-mode member's plan; members cannot leave plan mode themselves. Resume retries a failed launch. Returns per-member outcomes.", schema(map[string]any{"action": enum("pause", "resume", "end", "interrupt", "checkpoint", "configure"), "member_ids": strings, "node": str, "configs": configs, "body": str}, "action")},
		{"member_update", "Atomically set your status, complete/fail assignments and update QA. Results, QA bodies and evidence are at most 2000 bytes: put detail in a file and give its path. waiting returns at once: then END YOUR TURN; it clears your status unless this call sets one. waiting.until_assignments (ones you created) holds their results, and their assignees' answers and progress, for one wake-up when the last resolves; questions still wake you. A result may cc members, who get a non-waking copy. handoff (near the end of your context, or when asked; up to 32 KB, branch state and traps first) keeps what you did and know for the member that replaces you (handoff_from): Wash writes it under .wash/local/handoffs and tells the orchestrator. QA replies append and reach the thread's creator and assignee as answers; transitions need expected_revision; resolving needs evidence and the orchestrator's authority, or a reviewer's on the thread's node.", schema(map[string]any{"status": str, "emoji": str, "handoff": str, "waiting": schema(map[string]any{"reason": str, "reply_to": str, "until_assignments": strings}, "reason"), "assignment_results": array(result), "qa_updates": array(qa), "request_id": str})},
		{"message_send", "Send one message, or several atomically as messages. Recipients by member ID or key; a member's messages to the orchestrator are at most 2000 bytes. instruction/question/answer wake idle members; progress does not, except that your latest progress to the orchestrator is delivered when you then set waiting. qa:{action:open,id,node,title} opens a thread about a plan node (assignee defaults to recipient; on_behalf_of names the member whose question it is); later replies carry thread_id, and an answer on a thread also reaches its creator, assignee, on_behalf_of and everyone who has written on it. Thread messages are at most 2000 bytes. priority:\"checkpoint\" on an instruction leads the recipient's next turn as its one ask and supersedes your earlier queued instructions to it.", schema(messageInput)},
		{"inbox_read", "Read your retained inbox history; new messages already arrive in your turn. after is a message ID; limit 1–100.", schema(map[string]any{"after": str, "limit": integer})},
		{"message_retry", "Orchestrator: retry an uncertain delivery after reconciling it; it may already have run.", schema(map[string]any{"id": str}, "id")},
		{"assignment_update", "Create assignments (spawning authority; Wash returns each id, so create takes none) or complete/fail your own; only the assignee completes or fails one. On create, text is the one-line title the plan shows and body the instructions to work from; both reach the assignee. On complete/fail, body is the result. Every assignment is on a plan node: node, or the member's own. Creating one makes the node active; its result makes it reported (failed on failure). Work on a node whose needs are not done is refused unless override gives the reason, which the node records once. A member does one assignment at a time; a resident with one open takes one more, queued, delivered when the open one resolves. wait:{reason} sets you waiting on the assignments this call creates, as one set (their results arrive together; then END YOUR TURN). Residents stay for follow-up; ephemeral members retire after the turn.", schema(map[string]any{"updates": array(assignment), "wait": schema(map[string]any{"reason": str}, "reason"), "request_id": str}, "updates")},
		{"decision_request", "Ask the owner: 1–10 questions, each with options (pick one, or several with multi), a recommended option, and room for the owner's own words; any may be skipped. Ask here, never as a list of questions in prose. It blocks you: END YOUR TURN after the call; the owner's answers arrive as your next message and nothing else reaches you until then. thread_id records the questions and the answers, word for word, in that QA thread; the answer does not resolve it.", schema(map[string]any{"title": str, "questions": array(question), "thread_id": str, "request_id": str}, "questions")},
		{"plan_get", "Read the plan: one line per node in tree order (id · state · title · unmet needs · who is on it), the legend and revision. Each member on a node shows with its activity and context share. node or detail:true adds bodies, assignments and threads, each with the revision its edits and transitions need. Answer status questions from this.", schema(map[string]any{"node": str, "detail": boolean})},
		{"plan_set", "Orchestrator (the Architect for nodes not started): upsert plan nodes by id in one call; omitted fields stay, null deletes a node. A node: title, emoji, template (milestone|package|step|note: how it is drawn), parent, needs (node or QA thread ids done first), body (at most 2000 bytes; link to pages), state (todo|active|reported|done|failed or your own word). expected_revision per node guards edits. Only the orchestrator sets done, with nothing open on the node. from loads a plan file (TOML [[node]] tables), replacing the plan while no work is open.", schema(map[string]any{"nodes": map[string]any{"type": "object", "additionalProperties": nullable(node)}, "from": str, "request_id": str})},
		{"plan_accept", "Orchestrator: set a node done and get its merge commit trailers (Plan-Node, QA threads, gates as run, each reviewer's verdict) and the plan and thread files to stage with it. Refused while work is open on it or inside it.", schema(map[string]any{"node": str, "gates": array(gate), "request_id": str}, "node")},
		{"flash_message", "Display an attributed desktop-wide milestone/blocker notification without blocking work.", schema(map[string]any{"text": str, "emoji": str, "level": enum("info", "warning", "error")}, "text")},
	}
}
