package workspacemcp

// leadOnly tools always fail for a launched member (the store refuses them), so
// a member's tool list leaves their schemas out of every turn's prompt.
var leadOnly = map[string]bool{"workspace_configure": true, "workspace_end": true, "message_retry": true, "member_control": true, "plan_accept": true}

// MemberTools is Tools without the orchestrator-only operations.
func MemberTools() []Tool {
	var out []Tool
	for _, t := range Tools() {
		if !leadOnly[t.Name] {
			out = append(out, t)
		}
	}
	return out
}

func Tools() []Tool {
	str := field("string")
	boolean := field("boolean")
	integer := field("integer")
	strings := map[string]any{"type": "array", "items": str, "maxItems": 100}
	array := func(items any) any { return map[string]any{"type": "array", "items": items, "maxItems": 100} }
	enum := func(values ...string) any { return map[string]any{"type": "string", "enum": values} }
	configs := map[string]any{"type": "object", "additionalProperties": str}
	nullable := func(s any) any { return map[string]any{"anyOf": []any{s, field("null")}} }
	qa := schema(map[string]any{"id": str, "action": enum("open", "reply", "assign", "block", "resolve", "reopen"), "node": str, "title": str, "assignee": str, "body": str, "blocking": boolean, "expected_revision": integer, "decision_refs": strings, "evidence": str}, "id", "action")
	// A message's qa only opens a thread, and the thread's body is the message's.
	open := schema(map[string]any{"id": str, "action": enum("open"), "node": str, "title": str, "assignee": str, "blocking": boolean, "decision_refs": strings}, "id", "action")
	msgProps := map[string]any{"recipient": str, "type": enum("instruction", "question", "answer", "progress"), "body": str, "reply_to": str, "assignment_id": str, "request_id": str, "thread_id": str, "qa": open}
	msg := schema(msgProps, "recipient", "type", "body")
	assignment := schema(map[string]any{"action": enum("create", "complete", "fail"), "id": str, "member_id": str, "node": str, "override": str, "text": str, "body": str, "request_id": str, "cc": strings}, "action")
	// member_update reports results; it never creates an assignment.
	result := schema(map[string]any{"action": enum("complete", "fail"), "id": str, "body": str, "cc": strings}, "action", "id", "body")
	member := schema(map[string]any{"name": str, "catalog": str, "capability": enum("reviewer"), "approval": enum("ask", "auto"), "provider": str, "model": str, "effort": str, "configs": configs, "subagents": enum("allow", "deny"), "cwd": str, "instructions": str, "lifetime": enum("resident", "ephemeral"), "task": str, "can_spawn": boolean, "node": str, "role": enum("architect", "implementer", "reviewer"), "handoff_from": str}, "name", "instructions", "lifetime")
	node := schema(map[string]any{"title": str, "emoji": str, "template": enum("milestone", "package", "step", "note"), "parent": str, "needs": strings, "body": str, "state": str, "expected_revision": integer})
	gate := schema(map[string]any{"command": str, "exit_code": integer}, "command", "exit_code")
	option := schema(map[string]any{"label": str, "description": str}, "label")
	question := schema(map[string]any{"id": str, "header": str, "question": str, "options": array(option), "multi": boolean, "recommended": str}, "question")
	messageInput := map[string]any{"messages": array(msg), "request_id": str}
	// One message and a batch share the same tool.
	for k, v := range msgProps {
		messageInput[k] = v
	}
	return []Tool{
		{"workspace_get", "Read the workspace. Default view=team: per member state, activity, status, open assignments, undelivered mail and settings. view=state: full JSON with configuration, plan, assignments, pending decisions and each live session's config_options; include_messages with after/limit pages history. view=qa: the thread index (id, node, title, state, assignee, revision); node filters; thread_id pages a thread's events (after, limit 1–100). view=about: operating guide, usable before setup. Read-only.", schema(map[string]any{"view": enum("state", "about", "qa", "team"), "include_messages": boolean, "after": str, "limit": integer, "thread_id": str, "node": str})},
		{"workspace_configure", "Orchestrator: create (workspace.name; project_root defaults to your cwd, and members' cwd to project_root) or atomically patch the workspace. Omitted fields stay; null deletes. The plan is plan_set's: add nodes there before members that work on them. members are keyed launch definitions, each on a plan node (node) or on the team (none); a member's task is an assignment on its node: retries reuse a key, an existing one cannot change. A member's model is a slot of the workspace catalog (frontier|coding|small) or a model id; catalog defaults to yours and members may name another. qa_dir (e.g. \".wash/qa\", relative to project_root) keeps one Markdown file per QA thread, written as threads change; set on a new workspace it resumes the threads there (open ones whole, resolved ones as headers); null detaches it; check qa_document_status for write errors. plan_file (e.g. \".wash/plan.toml\") is where Wash writes the plan as it changes; legend says what your emojis and states mean; roles:{<role>:{instructions}} are put before each new member's own instructions by its role; context_warn (0–1) is the share of a member's context window at which you hear about it. from reads the definition from a TOML file (e.g. \".wash/workspace.toml\": name, max_active, max_members, catalog, qa_dir, plan_file, legend, context_warn, [roles.<role>], [members.<key>]); fields in the call win and members merge by key. preview validates only; expected_revision guards. Configuration commits before launches: inspect each launch outcome and resume failures with member_control. capability:reviewer is provider-enforced read/search plus coordination; subagents:deny removes the provider's own subagent tool; unsupported adapters fail launch.", schema(map[string]any{"workspace": schema(map[string]any{"name": str, "project_root": str}, "name"), "name": str, "max_active": integer, "max_members": integer, "catalog": str, "legend": str, "context_warn": field("number"), "roles": map[string]any{"type": "object", "additionalProperties": nullable(schema(map[string]any{"instructions": str}, "instructions"))}, "from": str, "members": map[string]any{"type": "object", "additionalProperties": member}, "qa_dir": nullable(str), "plan_file": nullable(str), "expected_revision": integer, "request_id": str, "preview": boolean})},
		{"workspace_end", "Orchestrator: end the workspace's child sessions, keeping the owning conversation, files and history. Refused while plan nodes are active or reported unless confirm:true. Returns the final QA save status; failed saves keep retrying. workspace_id (full ID or a unique prefix of at least 8) ends another workspace whose orchestrator is not running in Wash, e.g. a stale one still holding a QA file.", schema(map[string]any{"workspace_id": str, "confirm": boolean})},
		{"member_control", "Orchestrator: pause, resume, interrupt or end members by ID/key, or every member on a plan node (and inside it). interrupt ends the current turn and leaves the member available (pause also stops dispatch until resumed). configure (orchestrator) changes a member's adapter settings, live and on every resume, e.g. configs:{mode:\"default\"} once you approve a plan-mode member's plan; members cannot leave plan mode themselves. Resume retries a failed launch. Returns per-member outcomes.", schema(map[string]any{"action": enum("pause", "resume", "end", "interrupt", "configure"), "member_ids": strings, "node": str, "configs": configs}, "action")},
		{"member_update", "Atomically set your status, complete/fail assignments and update QA. Results, QA bodies and evidence are at most 2000 bytes: put detail in a file and give its path. waiting returns at once: then END YOUR TURN; it clears your status unless this call sets one. waiting.until_assignments (ones you created) holds their results, and their assignees' answers and progress, for one wake-up when the last resolves; questions still wake you. A result may cc members, who get a non-waking copy. handoff (near the end of your context, or when asked) keeps what you did and know for the member that replaces you (handoff_from). QA replies append and reach the thread's creator and assignee as answers; transitions need expected_revision; resolving needs evidence and the orchestrator's authority, or a reviewer's on the thread's node.", schema(map[string]any{"status": str, "emoji": str, "handoff": str, "waiting": schema(map[string]any{"reason": str, "reply_to": str, "until_assignments": strings}, "reason"), "assignment_results": array(result), "qa_updates": array(qa), "request_id": str})},
		{"message_send", "Send one message, or several atomically as messages. Recipients by member ID or key; a member's messages to the orchestrator are at most 2000 bytes. instruction/question/answer wake idle members; progress does not, except that your latest progress to the orchestrator is delivered when you then set waiting. qa:{action:open,id,node,title} opens a thread about a plan node (assignee defaults to recipient); later replies carry thread_id, and an answer on a thread also reaches its creator and assignee. Thread messages are at most 2000 bytes.", schema(messageInput)},
		{"inbox_read", "Read your retained inbox history; new messages already arrive in your turn. after is a message ID; limit 1–100.", schema(map[string]any{"after": str, "limit": integer})},
		{"message_retry", "Orchestrator: retry an uncertain delivery after reconciling it; it may already have run.", schema(map[string]any{"id": str}, "id")},
		{"assignment_update", "Create assignments (spawning authority; Wash returns each id, so create takes none) or complete/fail your own; only the assignee completes or fails one. Every assignment is on a plan node: node, or the member's own. Creating one makes the node active; its result makes it reported (failed on failure). Work on a node whose needs are not done is refused unless override gives the reason, which the node records. wait:{reason} sets you waiting on the assignments this call creates, as one set (their results arrive together; then END YOUR TURN). Residents stay for follow-up; ephemeral members retire after the turn.", schema(map[string]any{"updates": array(assignment), "wait": schema(map[string]any{"reason": str}, "reason"), "request_id": str}, "updates")},
		{"decision_request", "Ask the owner: 1–10 questions, each with options (pick one, or several with multi), a recommended option, and room for the owner's own words; any may be skipped. Ask here, never as a list of questions in prose. It blocks you: END YOUR TURN after the call; the owner's answers arrive as your next message and nothing else reaches you until then. thread_id records the questions and the answers, word for word, in that QA thread; the answer does not resolve it.", schema(map[string]any{"title": str, "questions": array(question), "thread_id": str, "request_id": str}, "questions")},
		{"plan_get", "Read the plan: one line per node in tree order (id · state · title · unmet needs · who is on it), the legend and revision. node or detail:true adds bodies, assignments and threads. Answer status questions from this.", schema(map[string]any{"node": str, "detail": boolean})},
		{"plan_set", "Orchestrator (the Architect for nodes not started): upsert plan nodes by id in one call; omitted fields stay, null deletes a node. A node: title, emoji, template (milestone|package|step|note: how it is drawn), parent, needs (node or QA thread ids done first), body (at most 2000 bytes; link to pages), state (todo|active|reported|done|failed or your own word). expected_revision per node guards edits. Only the orchestrator sets done, with nothing open on the node. from loads a plan file (TOML [[node]] tables), replacing the plan while no work is open.", schema(map[string]any{"nodes": map[string]any{"type": "object", "additionalProperties": nullable(node)}, "from": str, "request_id": str})},
		{"plan_accept", "Orchestrator: set a node done and get its merge commit trailers (Plan-Node, QA threads, gates as run, each reviewer's verdict) and the plan and thread files to stage with it. Refused while work is open on it or inside it.", schema(map[string]any{"node": str, "gates": array(gate), "request_id": str}, "node")},
		{"flash_message", "Display an attributed desktop-wide milestone/blocker notification without blocking work.", schema(map[string]any{"text": str, "emoji": str, "level": enum("info", "warning", "error")}, "text")},
	}
}
