//go:build multicall && !no_app_session_summary

// Code generated by `make gen-imports` from the Makefile app roster; DO NOT EDIT.
package main

import _ "github.com/sirmick/wash/apps/session-summary/be"
