// Code generated by `make gen-agent-protocol` from internal/agentproto; DO NOT EDIT.
//
// The protocol between com.wash.agentd and its frontends (docs/AGENT_PROTOCOL.md).

/** The protocol version agentd sends on every State (agentproto.Version). */
export const AGENT_PROTOCOL_VERSION = 1;

/**
 * Adapter is one way to reach an agent over ACP, as the launcher shows it:
 * whether this box can start it, and if not, why.
 */
export interface Adapter {
  /** ID is what the launcher and the roster call this agent. */
  id: string;
  /** Name is what a human reads. */
  name: string;
  /** Note explains a greyed row: why this one cannot be used here. */
  note?: string;
  /** Available is whether it can be launched here. */
  available: boolean;
}

/**
 * AdapterOptions is what one adapter offered the last time a session of it
 * started here (agentd remembers it across restarts).
 */
export interface AdapterOptions {
  /** Adapter is the adapter id ("claude", "codex", …). */
  adapter: string;
  /** Version is the adapter's own version string, as it introduced itself. */
  version?: string;
  /**
   * Modes are its approval presets; Configs its settings, of which the
   * ones in the "model" and "thought_level" categories are the model and
   * effort lists. Current values are those of the session that reported
   * them and mean nothing here.
   */
  modes?: Mode[];
  configs?: Config[];
}

/** AgentAddRoot widens which folders a session may reach beyond its cwd. */
export interface AgentAddRoot {
  kind: 'agent_add_root';
  key: string;
  path: string;
}

/** AgentAnswer answers a question (Ask) by its id. */
export interface AgentAnswer {
  kind: 'agent_answer';
  id: string;
  /** Decision is allow | deny. */
  decision: string;
  /**
   * Remember writes Rule (or the ask's suggested rule) to the policy, so
   * the question is not asked again.
   */
  remember: boolean;
  rule: string;
  /**
   * Scope picks the table a remembered answer is written to: "" (or
   * anything unrecognised) is the global one, "workspace" is the asking
   * member's workspace's. An unknown value must not silently widen
   * anything, so it falls back to the narrower, global behaviour.
   */
  scope?: string;
}

/**
 * AgentCancel ends the running turn; the agent answers with a cancelled
 * stop.
 */
export interface AgentCancel {
  kind: 'agent_cancel';
  key: string;
}

/** AgentDefaultPrompt asks for the stored default prompt's text. */
export interface AgentDefaultPrompt {
  kind: 'agent_default_prompt';
}

/** AgentDelete deletes a stored session that is not running. */
export interface AgentDelete {
  kind: 'agent_delete';
  session_id: string;
}

/**
 * AgentDeleteCatalog removes a catalog from agents.json: a built-in goes
 * back to what wash ships, the user's own is gone.
 */
export interface AgentDeleteCatalog {
  kind: 'agent_delete_catalog';
  id: string;
}

/**
 * AgentDetach leaves a session running with no window: its roster row
 * stays and offers Reattach, and its controller window is told to close.
 */
export interface AgentDetach {
  kind: 'agent_detach';
  key: string;
}

/**
 * AgentHistory searches the stored sessions: their metadata and, with a
 * query, their conversations.
 */
export interface AgentHistory {
  kind: 'agent_history';
  query?: string;
  /** Limit bounds the answer; 0 and anything above 200 mean 200. */
  limit?: number;
  /**
   * All includes the sessions a workspace launched (its members). Without
   * it the answer is top-level sessions only: one orchestrator can launch
   * dozens of members, and they buried the conversations people started.
   */
  all?: boolean;
}

/** AgentProfile describes launch settings and an optional enforced capability profile. */
export interface AgentProfile {
  capability?: string;
  /**
   * Approval "auto" launches the member with host auto-approval on; ""
   * and "ask" leave every unmatched tool call to the human.
   */
  approval?: string;
  provider: string;
  /**
   * Connection names how the provider is reached ("opencode@openrouter");
   * empty is the provider direct. agentd owns the list and checks it.
   */
  connection?: string;
  model?: string;
  effort?: string;
  configs?: Record<string, string>;
  /**
   * Subagents "deny" removes the provider's own subagent tool, so the
   * member's work stays in its transcript and the workspace's accounting.
   * "" and "allow" leave it available.
   */
  subagents?: string;
  /**
   * Enforcement is what capability:"reviewer" requires of the adapter.
   * "" ("advisory" too) launches on any provider and records in
   * Member.Applied how far the read-only restriction actually held;
   * "adapter" refuses to launch unless the adapter enforces it at a
   * version Wash has verified. Wash is agnostic to the provider, so the
   * advisory default is the rule and the strict value the exception.
   */
  enforcement?: string;
}

/**
 * AgentPrompt is another turn on a live session. Sent while a turn runs,
 * it is queued and sent when the turn ends.
 */
export interface AgentPrompt {
  kind: 'agent_prompt';
  key: string;
  text?: string;
  /**
   * Blocks are attachments sent with the text: a pasted image, a file
   * the composer's Attach button picked. Kept as a wash-shaped struct
   * rather than acp.ContentBlock so the app→service wire is ours to
   * validate — the router carries this from a window, and a window is
   * not trusted to name a mime type or a path.
   */
  blocks?: PromptAttachment[];
}

/** AgentPrune deletes stored sessions older than MaxAgeMS. */
export interface AgentPrune {
  kind: 'agent_prune';
  /**
   * MaxAgeMS is how old a session must be to go; 0 means every stored
   * session that is not running. A duration rather than a cutoff so a
   * browser clock on another machine cannot be the one deciding.
   */
  max_age_ms: number;
}

/**
 * AgentQuestionAnswer answers a Question by its id: accept with the
 * answers (question id to answer; a question left out is skipped), or
 * decline.
 */
export interface AgentQuestionAnswer {
  kind: 'agent_question_answer';
  id: string;
  /** Action is accept | decline. */
  action: string;
  answers?: Record<string, QuestionAnswer>;
}

/** AgentReattach opens a window onto a running session. */
export interface AgentReattach {
  kind: 'agent_reattach';
  key: string;
}

/** AgentRemoveRoot narrows it again. */
export interface AgentRemoveRoot {
  kind: 'agent_remove_root';
  key: string;
  path: string;
}

/**
 * AgentRename names a session, by roster key when it is running or by
 * session id when it is not. An empty title clears the person's name and
 * the agent's own shows again.
 */
export interface AgentRename {
  kind: 'agent_rename';
  key?: string;
  session_id?: string;
  title: string;
}

/**
 * AgentResume reopens a stored session: session/load replays it, and an
 * Agent window opens on it (or the one already showing it comes forward).
 */
export interface AgentResume {
  kind: 'agent_resume';
  session_id: string;
}

/**
 * AgentSetCatalog stores one catalog under agents.json `catalogs`, whole,
 * as the Setup tab holds it. For a built-in catalog this is its override;
 * for any other id it is the user's own.
 */
export interface AgentSetCatalog {
  kind: 'agent_set_catalog';
  id: string;
  catalog: CatalogSpec;
}

/**
 * AgentSetConfig changes one of the agent's own settings (Row.Configs):
 * model, reasoning effort, plan mode, …
 */
export interface AgentSetConfig {
  kind: 'agent_set_config';
  key: string;
  id: string;
  value: string;
}

/**
 * AgentSetDefaultPrompt stores the default prompt. Empty text is a
 * deletion, not a validation failure.
 */
export interface AgentSetDefaultPrompt {
  kind: 'agent_set_default_prompt';
  text: string;
}

/**
 * AgentSetKey stores a connection key (State.Keys), or clears it with an
 * empty value. The value is never sent back.
 */
export interface AgentSetKey {
  kind: 'agent_set_key';
  name: string;
  value?: string;
}

/**
 * AgentSetLaunch stores the launcher's remembered permission default
 * (State.Launch), whole.
 */
export interface AgentSetLaunch {
  kind: 'agent_set_launch';
  launch: LaunchPrefs;
}

/** AgentSetMode switches the agent's approval preset (Row.Modes). */
export interface AgentSetMode {
  kind: 'agent_set_mode';
  key: string;
  mode: string;
}

/** AgentSetYolo turns host-side auto-approval on or off for one session. */
export interface AgentSetYolo {
  kind: 'agent_set_yolo';
  key: string;
  on: boolean;
}

/** AgentStart starts a session. */
export interface AgentStart {
  kind: 'agent_start';
  /**
   * Catalog and Model choose the settings (catalogs.go): Model is a slot
   * of a curated catalog (frontier, coding, small; frontier when empty)
   * or a model id the catalog's adapter offers (empty is its default on
   * an auto catalog). Agent alone, with no catalog, is how `wash ai
   * --agent` starts: that adapter on its defaults.
   */
  catalog?: string;
  model?: string;
  agent?: string;
  /**
   * Configs are the launcher's Advanced settings, by the adapter's own
   * option ids (effort, fast mode, …), applied over the catalog's.
   */
  configs?: Record<string, string>;
  /**
   * Mode is the adapter session mode to start in (State.Launch's default
   * unless the launcher's Permissions row was changed for this start);
   * empty is the adapter's default. Yolo starts with host-side
   * auto-approval on.
   */
  mode?: string;
  yolo?: boolean;
  /** Cwd is the folder the session works in; empty is the home folder. */
  cwd: string;
  /** Prompt is sent as the first turn, after the stored default prompt. */
  prompt?: string;
  /**
   * Open asks agentd to open (or focus) an Agent window on the new
   * session, for a starter that is not itself that window (the manager).
   */
  open?: boolean;
  /**
   * Claim makes the starter the session's controller (see Roles): an
   * Agent window starting the session it will show.
   */
  claim?: boolean;
  /**
   * ReqID is opaque to agentd and echoed back on agent_started, success
   * or failure. A host with ONE session per process (wash-ai) never needs
   * it — the reply can only be about the one thing it asked for. A host
   * with several (wash-edit's agent tabs) cannot tell two concurrent
   * starts apart without it, and a FAILED start carries no key at all, so
   * there would be nothing to attribute the error to.
   */
  req_id?: string;
}

/** AgentStarted answers AgentStart: the new session's key, or why it failed. */
export interface AgentStarted {
  kind: 'agent_started';
  key?: string;
  session_id?: string;
  req_id?: string;
  error?: string;
}

/** AgentStop ends a session and its adapter. */
export interface AgentStop {
  kind: 'agent_stop';
  key: string;
}

/**
 * AgentTestKey checks a key against its provider: the typed value, or the
 * stored one when Value is empty.
 */
export interface AgentTestKey {
  kind: 'agent_test_key';
  name: string;
  value?: string;
}

/**
 * Applied is what a launch did with a member's advisory settings: the
 * provider decides what it can enforce, Wash records the outcome instead of
 * refusing. Read beside LaunchSettings, which is what was asked.
 */
export interface Applied {
  /**
   * Enforcement of capability "reviewer": "adapter" (the adapter's own
   * tool allowlist, verified, plus Wash's host guards), "unverified"
   * (the same allowlist on an adapter version Wash has not verified), or
   * "host" (Wash's guards only: file writes and terminals refused through
   * its ACP layer, edit/execute permissions denied, coordination tools
   * scoped; the adapter's own tools unrestricted).
   */
  enforcement?: string;
  /**
   * Subagents is how subagents "deny" held: "denied" (the adapter's
   * subagent tool removed) or "instructed" (the adapter has no such
   * control; the member is told not to).
   */
  subagents?: string;
  /**
   * Notes are launch settings the adapter did not offer or did not keep,
   * one line each, e.g. a model id not in its list; the session runs on
   * what the adapter chose instead.
   */
  notes?: string[];
}

/**
 * Ask is one question waiting for a human. It rides the roster's own
 * state push, so the sidebar needs no second subscription.
 */
export interface Ask {
  /** ID is agentd's handle for this question; the answer names it. */
  id: string;
  /**
   * Agent / Tool / Subject are what the human reads: "claude wants to
   * run `git push origin main`".
   */
  agent: string;
  tool: string;
  subject?: string;
  cwd?: string;
  dir?: string;
  /**
   * SuggestedRule is what "Always allow" would write. Shown ON the
   * button — what you clicked is what gets saved.
   */
  suggested_rule?: string;
  /**
   * RuleCwd is the directory that rule would be confined to, when it
   * would be (agentpolicy.RuleScope): a Bash rule from one project must
   * not buy the same command in every other checkout.
   */
  rule_cwd?: string;
  /**
   * RowKey ties the question to its roster row (same "<instance>:<chan>"
   * key for terminals; hosted sessions mint their own), so the sidebar
   * can render it against the right agent.
   */
  row_key: string;
  /**
   * WorkspaceName is set when the asking session is a workspace member,
   * and is what lets the prompt offer "always, for this workspace"
   * alongside the global "always". The ID is deliberately NOT sent: the
   * answer names a scope, never a target (see the answer path).
   */
  workspace_name?: string;
  /** AgeMS is how long it has been waiting, as of the push. */
  age_ms: number;
}

export interface Assignment {
  id: string;
  assigner: string;
  member_id: string;
  /** Node is the plan node the work is on. */
  node?: string;
  text: string;
  state: string;
  result?: string;
}

/**
 * Attach hands a window agentd opened the session it is to show; the lease
 * is already its.
 */
export interface Attach {
  kind: 'attach';
  key: string;
}

/** CatalogSaved answers AgentSetCatalog and AgentDeleteCatalog. */
export interface CatalogSaved {
  kind: 'catalog_saved';
  id: string;
  error?: string;
}

/**
 * CatalogSpec is a catalog as written: a name and either an adapter (an
 * auto catalog, listing what that adapter offers) or three slots.
 */
export interface CatalogSpec {
  name: string;
  adapter?: string;
  connection?: string;
  /**
   * Slots is keyed by slot name (frontier, coding, small); all three are
   * required for a curated catalog, and none is given for an auto one.
   */
  slots?: Record<string, SlotSpec>;
}

/**
 * CatalogView is a catalog as the launcher and the Setup tab show it. A
 * catalog is either an adapter's own model list (Adapter set, no Slots:
 * what the adapter reports is what the Model select offers) or a curated
 * set of three slots, frontier, coding and small, each a model on an
 * adapter.
 */
export interface CatalogView {
  id: string;
  name: string;
  /**
   * Adapter and Connection are an auto catalog's: the adapter whose
   * models it lists, reached direct or through the connection.
   */
  adapter?: string;
  connection?: string;
  /**
   * Available is every slot (or the adapter) startable here; Note says
   * why not.
   */
  available: boolean;
  note?: string;
  slots?: SlotView[];
  /**
   * Builtin is a catalog wash ships (catalogs.json); Overridden says
   * agents.json changes it. A catalog that is neither is the user's
   * own. The Setup tab offers "reset" for an overridden built-in and
   * "delete" for the user's own.
   */
  builtin?: boolean;
  overridden?: boolean;
}

/**
 * ClaimDenied refuses the lease: another instance holds it, and has been
 * raised. A window denied its session closes.
 */
export interface ClaimDenied {
  kind: 'claim_denied';
  key: string;
}

/** Command is one slash command the agent offers. */
export interface Command {
  name: string;
  description?: string;
}

/** Config is one agent setting the session can change. */
export interface Config {
  id: string;
  name: string;
  description?: string;
  /**
   * Category is the ACP category ("model", "thought_level", …), which is
   * how a setting is matched across adapters that name it differently.
   */
  category?: string;
  current?: string;
  values?: ConfigValue[];
}

export interface ConfigValue {
  value: string;
  name: string;
  description?: string;
}

/**
 * ConnectionView is one named connection: which adapter it launches, and
 * the key it needs, if any.
 */
export interface ConnectionView {
  id: string;
  adapter: string;
  key?: string;
}

/** DefaultPrompt is the stored default prompt's text, answering either. */
export interface DefaultPrompt {
  kind: 'default_prompt';
  text: string;
}

/**
 * Detach tells a session's controller window that the session was
 * detached elsewhere (the rail, the manager), so it closes.
 */
export interface Detach {
  kind: 'detach';
  key: string;
}

/**
 * Event is one line in a transcript.
 * 
 * Flat and string-typed on purpose: this crosses the router to the FE, and
 * structured byte fields get base64'd on the way (the CBOR pitfall).
 */
export interface Event {
  seq: number;
  /**
   * Kind is one of the Event* kinds above: message | thought | tool |
   * decision | user | terminal | image | collaboration.
   */
  kind: string;
  /** Text is the message body, accumulated across streamed chunks. */
  text?: string;
  /** Tool fields, set when Kind == EventTool. */
  tool_id?: string;
  tool_kind?: string;
  title?: string;
  status?: string;
  /**
   * Path is the file a tool call touched (its first ACP location, or
   * the diff's), so a host can open it. Diff is the unified diff of what
   * the call changed, rendered once here from the agent's before/after
   * pair (diff.go). Both on EventTool only.
   */
  path?: string;
  diff?: string;
  /** Mime is set on EventImage; Text then holds the base64 bytes. */
  mime?: string;
  /** Reason and Detail are set on EventDecision. */
  reason?: string;
  detail?: string;
  /** Channel is set on EventTerminal: the raw channel id to render. */
  channel?: number;
  /** AtMS is wall-clock at first append, for the FE's own clock anchoring. */
  at_ms: number;
  /**
   * Append marks a wire-only delta: Text is what was ADDED to the event
   * with this Seq since the last emit, not the whole message. Never set
   * on a stored or snapshotted event (transcript_emit.go).
   */
  append?: boolean;
  /**
   * TextLen is the message's byte length after this event applies, on
   * message/thought events. A consumer applying a delta checks its own
   * length + the delta against it, and asks for a replay on mismatch.
   */
  text_len?: number;
}

/**
 * Focus asks for a session's window to come forward, opening one if
 * nothing is showing it. The shell sends it when a notification about the
 * session is clicked; frontends send it to go to a running session.
 */
export interface Focus {
  kind: 'wash.focus';
  key: string;
}

/**
 * History answers AgentHistory, newest first, each session stamped with
 * what the roster says about it now.
 */
export interface History {
  kind: 'history';
  query: string;
  sessions: SessionMeta[] | null;
}

/** HistoryDeleted answers AgentDelete. */
export interface HistoryDeleted {
  kind: 'history_deleted';
  session_id: string;
  error?: string;
}

/** HistoryPruned answers AgentPrune: how many sessions went. */
export interface HistoryPruned {
  kind: 'history_pruned';
  deleted: number;
}

/** KeySaved answers AgentSetKey. */
export interface KeySaved {
  kind: 'key_saved';
  name: string;
  error?: string;
}

/** KeyTest answers AgentTestKey with what the provider said. */
export interface KeyTest {
  kind: 'key_test';
  name: string;
  ok: boolean;
  detail: string;
}

/** KeyView is a key as the launcher shows it. */
export interface KeyView {
  id: string;
  name: string;
  set: boolean;
  /** Hint is the stored key's last four characters. */
  hint?: string;
  testable?: boolean;
}

/**
 * LaunchPrefs is the remembered default for a launch: the catalog and model
 * "start an agent" means, and the two permission settings it starts with —
 * the adapter's own approval preset and wash's auto-approval.
 */
export interface LaunchPrefs {
  /**
   * Catalog is the catalog id a start that names none of its own uses,
   * and Model the slot or model id within it. This is what the Editor's
   * "new agent here", the Places agent icon and `wash ai <dir>` all
   * resolve against, so one setting decides what starting an agent means
   * everywhere (docs/PLACES.md §4.5).
   */
  catalog?: string;
  model?: string;
  /**
   * Mode is the adapter's session mode to start in, by adapter id: the
   * names are the adapter's own ("acceptEdits" on Claude Code, "read-only"
   * on Codex), so one remembered value cannot serve two adapters.
   */
  mode?: Record<string, string>;
  /** Yolo starts every session with host-side auto-approval on. */
  yolo?: boolean;
}

/**
 * ManagerState is the Agents manager's view of the roster: every row with
 * its transcript preview and workspace placement, without the per-session
 * settings only a controller needs.
 */
export interface ManagerState {
  kind: 'manager_state';
  state: State;
}

/**
 * ManagerSubscribe registers the sender as a manager and asks for the
 * manager's roster view, now and on every change.
 */
export interface ManagerSubscribe {
  kind: 'manager_subscribe';
}

export interface Member {
  key?: string;
  /**
   * Node is the plan node the member works on; empty is the team (the
   * orchestrator, an Architect).
   */
  node?: string;
  role?: string;
  instructions?: string;
  initial_task?: string;
  /**
   * InitialOverride is why the initial task starts before what its node
   * needs is done; recorded on the node when the task is assigned.
   */
  initial_override?: string;
  /**
   * Handoff is the handoff a member launched with handoff_from reads in
   * its first message: what the member it replaces had done and knew.
   */
  handoff?: string;
  usage?: Usage;
  /**
   * Catalog and Model are what the member was asked to run on: the
   * catalog (the workspace's unless the member named one) and the model
   * as given, a slot name or an id. LaunchSettings is what that resolved
   * to, with the member's own settings on top, fixed when its key was
   * reserved: a later catalog change moves no running member.
   */
  catalog?: string;
  model?: string;
  launch_settings?: AgentProfile;
  initial_configs?: Record<string, string>;
  /**
   * Applied is what the launch made of the advisory settings (reviewer
   * enforcement, subagents, settings the adapter did not take).
   */
  applied?: Applied;
  /**
   * Adjusted are settings the orchestrator changed on the live member
   * (member_control configure), applied over LaunchSettings on every
   * resume. Kept apart so the keyed launch definition stays as declared.
   */
  adjusted_configs?: Record<string, string>;
  /**
   * AutoApprove is whether host auto-approval is on for this member now:
   * set from Approval at launch, and by the human's toggle afterwards.
   * Kept here, not on the session, so a restart (which pauses rather
   * than ends a member) does not silently switch it off; it ends with
   * the workspace, never outliving the job it was granted for.
   */
  auto_approve?: boolean;
  id: string;
  name: string;
  provider: string;
  cwd: string;
  session_id: string;
  creator: string;
  lifetime: string;
  state: string;
  status?: string;
  emoji?: string;
  waiting?: string;
  waiting_for?: string;
  /**
   * WaitingOn is a set of assignments this member created and is waiting
   * for as a whole: their results are held and delivered together in one
   * turn once every one has completed or failed. One wake-up per review
   * round instead of one per reviewer.
   */
  waiting_on?: string[];
  status_updated_at?: number;
  can_spawn: boolean;
  retire?: boolean;
}

export interface Message {
  thread_id?: string;
  id: string;
  swarm_id: string;
  sender: string;
  recipient: string;
  type: string;
  body: string;
  reply_to?: string;
  assignment_id?: string;
  request_id?: string;
  delivery: string;
  created_at: number;
  /**
   * Dispatched is when the message went into a prompt; Settled when its
   * delivery state last became terminal (delivered, uncertain, cancelled,
   * superseded). With Created they are the watermarks an orchestrator
   * reads to tell "in the member's transport queue" from "in the turn it
   * is reasoning in" from "done" — the distinction two live workspaces
   * could not make and so re-sent permissions and stop requests blind.
   */
  dispatched_at?: number;
  settled_at?: number;
  /**
   * Priority "checkpoint" puts an instruction ahead of everything else
   * queued for its recipient, as the one ask of its next turn, and
   * supersedes the sender's earlier queued instructions to it: a stop or
   * save request must not wait its turn behind the work it is stopping.
   */
  priority?: string;
  /**
   * Task marks the instruction Assign wrote to hand its assignment over.
   * Only that one goes stale when the assignment resolves: a later
   * instruction naming the same assignment is a new ask about finished
   * work, not a duplicate of this one.
   */
  task?: boolean;
  /**
   * Questions is a decision_request's question set; Answers the owner's
   * answers on its decision_response.
   */
  questions?: QuestionSet;
  answers?: Record<string, QuestionAnswer>;
}

/** Mode is one approval/sandbox preset an agent offers. */
export interface Mode {
  id: string;
  name: string;
  description?: string;
}

/** Node is one plan node. */
export interface Node {
  id: string;
  title: string;
  emoji?: string;
  /**
   * Template is how the node is drawn: milestone, package, step or note.
   * Wash gives it no other meaning, except that a milestone with no
   * children is a sketch.
   */
  template?: string;
  /** Parent is the node this one sits inside. */
  parent?: string;
  /**
   * Needs are node IDs that must be done, or QA thread IDs that must be
   * resolved, before work on this node (or anything inside it) starts.
   */
  needs?: string[];
  body?: string;
  /**
   * State is todo, active, reported, done, failed, or a short word of the
   * orchestrator's own.
   */
  state: string;
  revision: number;
  /** Overrides record each start with needs unmet, and why. */
  overrides?: string[];
}

/**
 * Notify brings something to the person's attention. With a Key, activating
 * the notification sends wash.focus for that session.
 */
export interface Notify {
  kind: 'notify';
  key?: string;
  title: string;
  body?: string;
  /** Level is info | warn | error. */
  level: string;
}

/**
 * OpenSession opens a window showing a session. agentd has already
 * reserved the session's lease for it; the window is handed the session
 * with an attach push.
 */
export interface OpenSession {
  kind: 'open_session';
  key: string;
}

/** Option is one choice. */
export interface Option {
  label: string;
  description?: string;
}

/**
 * PendingQuestion is a question set waiting for the human, shown pinned above the
 * asking session's composer (and in its workspace tab) until answered.
 */
export interface PendingQuestion {
  /**
   * ID is agentd's handle; the answer names it. A workspace decision's is
   * its message id.
   */
  id: string;
  /** RowKey is the asking session's roster row. */
  row_key: string;
  agent?: string;
  /**
   * Source is elicitation (the adapter asked) or decision (a workspace
   * member's decision_request).
   */
  source: string;
  set: QuestionSet;
  /** WorkspaceName and MemberID place a workspace member's question. */
  workspace_name?: string;
  member_id?: string;
  /** AgeMS is how long it has been waiting, as of the push. */
  age_ms: number;
}

/**
 * PreviewPatch updates rows' transcript previews (Row.Preview) in the
 * manager's view.
 */
export interface PreviewPatch {
  kind: 'preview_patch';
  rows: PreviewRow[] | null;
}

/** PreviewRow is one row's preview. */
export interface PreviewRow {
  key: string;
  preview?: string;
}

/**
 * PromptAttachment is one attachment on its way to an ACP content block.
 * Type is "image" or "file"; anything else is dropped.
 */
export interface PromptAttachment {
  type: string;
  /** Image: base64 bytes and their mime type. */
  mime?: string;
  data?: string;
  /**
   * File: an absolute path, confined against the session cwd before it
   * becomes a resource_link.
   */
  path?: string;
  name?: string;
}

/**
 * QADocumentStatus is where a file (or directory) Wash writes for the
 * workspace stands on disk: the QA thread files, the plan file.
 */
export interface QADocumentStatus {
  path: string;
  /** State is unconfigured | pending | saved | error. */
  state: string;
  error?: string;
  updated_at?: number;
}

export interface QAEvent {
  id: string;
  author: string;
  kind: string;
  body: string;
  message_id?: string;
  created_at: number;
}

export interface QAThread {
  id: string;
  /** Node is the plan node the thread is about. */
  node: string;
  title: string;
  creator: string;
  assignee: string;
  state: string;
  blocking: boolean;
  revision: number;
  decision_refs: string[] | null;
  evidence?: string;
  /**
   * Participants are members the thread was opened on behalf of: an
   * implementer whose question the orchestrator framed for the Architect
   * hears the answer itself, as anyone who has written on the thread does.
   */
  participants?: string[];
  /**
   * Resumed marks a thread resolved in an earlier workspace and read
   * back from its QA file: its evidence is about that workspace's code.
   */
  resumed?: boolean;
  /**
   * Archived marks a resolved thread read back as a header only: its
   * events stay in its file until something needs them.
   */
  archived?: boolean;
  events: QAEvent[] | null;
}

/** Question is one question in a set. */
export interface Question {
  id: string;
  /** Header is a short label for the question (a chip, a tab). */
  header?: string;
  question: string;
  options?: Option[];
  /** Multi lets the owner pick several options. */
  multi?: boolean;
  /** Recommended is the label of the option the asker recommends. */
  recommended?: string;
  /**
   * NoText says only the options are answers (a form field with no free
   * text); a decision_request question always takes the owner's words.
   */
  no_text?: boolean;
}

/**
 * QuestionAnswer is the owner's answer to one question: the options picked,
 * their own words, or neither (skipped).
 */
export interface QuestionAnswer {
  selected?: string[];
  text?: string;
}

/** QuestionSet is one ask of the owner. */
export interface QuestionSet {
  title?: string;
  questions: Question[] | null;
}

/** Raise tells a session's controller to come forward. */
export interface Raise {
  kind: 'wash.focus';
  key: string;
}

/**
 * RosterState is the whole roster, sent by the StateService to every
 * subscriber on each change.
 */
export interface RosterState {
  kind: 'state';
  state: State;
}

/** Row is one hosted agent session. */
export interface Row {
  /**
   * Key identifies the session on the roster: "acp:<n>", minted by
   * agentd. Every session-scoped message names it.
   */
  key: string;
  /** Agent is the slug ("claude", "codex", …). */
  agent: string;
  /**
   * State is running | working | needs-input | done | failed, or
   * "stale" once an exited session's row is ageing out.
   */
  state: string;
  /**
   * Reason qualifies the state: which input is wanted (permission |
   * idle), or how a turn or session ended (cancelled, error, exited, …).
   */
  reason?: string;
  /**
   * SessionID is the agent's own session id — what makes a row
   * actionable later (`--resume`, copy-session-id).
   */
  session_id?: string;
  /**
   * Cwd is where the agent is working; Dir is its basename, which is
   * what a 300px sidebar column can actually show.
   */
  cwd?: string;
  dir?: string;
  /**
   * Branch / Dirty come from agentd shelling git in Cwd, lazily and
   * cached — never from the agent's hooks (§7).
   */
  branch?: string;
  dirty?: boolean;
  /**
   * Background is the work the session left running in the background
   * (a Bash run in the background): what it is, while it runs.
   */
  background?: string;
  /**
   * SinceMS is how long the row has been in this state, as of the push.
   * The FE anchors its own clock to it (no cross-clock comparison).
   */
  since_ms: number;
  /**
   * Used / Size are the agent's context accounting (usage_update), and
   * Title is its own name for the session (session_info_update).
   */
  used?: number;
  size?: number;
  title?: string;
  /**
   * Preview is populated only in the compact manager projection. Live
   * transcript changes arrive as bounded Bulk patches, never by
   * republishing the complete roster.
   */
  preview?: string;
  /**
   * Mode is the agent's active approval preset and Modes what it offers
   * (docs/AGENT_APP.md §9). Empty for an agent with no such notion.
   */
  mode?: string;
  modes?: Mode[];
  /**
   * Yolo is wash answering this session's permission questions with
   * "allow" instead of asking. Host-side and per-session; it is on the
   * row so every surface that shows the session can SAY so — an
   * auto-approving agent that looks like any other is the failure mode
   * this flag exists to prevent.
   */
  yolo?: boolean;
  /**
   * Configs is the agent's generic settings block (model, reasoning
   * effort, plan mode…). Commands are its own slash commands.
   */
  configs?: Config[];
  commands?: Command[];
  /**
   * Detached marks a session still running with no window pointing at
   * it — the sidebar offers Reattach rather than focus.
   */
  detached?: boolean;
  /**
   * Queued is how many prompts are waiting for the current turn to end
   * (docs/AGENT_MESSENGER.md semantics: a message typed mid-reply is
   * sent when the reply finishes, not dropped and not interleaved).
   */
  queued?: number;
  /**
   * Roots are folders this session may reach BEYOND its cwd (roots.go).
   * On the row because every surface that shows a session must be able
   * to say how wide it is: a session with three extra roots is a
   * different thing from one confined to its own folder, and only the
   * person who widened it would otherwise know.
   */
  roots?: string[];
  /**
   * Stale marks the row of a session that is no longer hosted: shown
   * greyed, then dropped.
   */
  stale?: boolean;
  /**
   * Workspace places the session in a workspace team, so the Agents
   * window lists members under the orchestrator that leads them. Set
   * only on the manager's projection.
   */
  workspace?: RowWorkspace;
}

/** RowWorkspace is one session's place in a workspace team. */
export interface RowWorkspace {
  id: string;
  name: string;
  /**
   * LeadSession is the orchestrator's session: a member row nests under
   * the row with this session_id.
   */
  lead_session: string;
  orchestrator?: boolean;
  member: string;
  role?: string;
  /** Node and NodeTitle are the plan node the member works on. */
  node?: string;
  node_title?: string;
}

/** Rule is one line of the table. */
export interface Rule {
  /** Match is `Tool` or `Tool(pattern)`. */
  match: string;
  /** Decision is allow | deny | ask. */
  decision: string;
  /** Cwd scopes the rule to requests at or under this directory. */
  cwd?: string;
}

/** Session is one remembered agent session. */
export interface Session {
  session_id: string;
  agent: string;
  /**
   * Connection is what a resume must launch through again; Catalog and
   * Model are what the launcher defaults to next time (launchRecord).
   */
  connection?: string;
  catalog?: string;
  model?: string;
  cwd?: string;
  dir?: string;
  /**
   * Title is what this session was ABOUT, in the agent's own words —
   * it names its sessions on session_info_update once it works out what
   * the work is. "codex · mick" tells you nothing a week later; "Fix
   * the reconnect banner race" does.
   */
  title?: string;
  /**
   * UserTitle is the name a PERSON gave the session (session_admin.go).
   * When set it is what publishHistory puts in Title; the agent's own
   * title stays here underneath so clearing the user's falls back to it.
   */
  user_title?: string;
  /**
   * LastSeen is unix seconds — an absolute the FE renders as "2h ago",
   * and the only field a keepalive touches.
   */
  last_seen: number;
  /**
   * Live is set on the way out to the FE: a session whose agent is
   * running right now is in the roster above, so the Recent list greys
   * it rather than offering to resume what is already here.
   */
  live?: boolean;
  /**
   * Detached is a live session with no window pointing at it.
   * 
   * Live and REACHABLE are not the same thing, and treating them as one
   * is what made the History menu useless in exactly the case you open
   * it for. agent_detach sets the flag and closes the window but never
   * retires the row, so a detached session is still "live" — and the
   * menu, which hides live sessions to avoid offering to duplicate a
   * running one, hid the one thing you were trying to get back.
   * 
   * A detached session is not something to resume. It is something to
   * reattach to, which is a different verb with a different outcome.
   */
  detached?: boolean;
  /**
   * RowKey is the roster key this session is running as, present only
   * while it has a row. Reattach is key-addressed, not session-id
   * addressed, so the menu needs this to offer the verb at all.
   */
  row_key?: string;
}

/** SessionClaim takes (or re-affirms) the controller lease on a session. */
export interface SessionClaim {
  kind: 'session_claim';
  key: string;
}

/** SessionClaimed grants the lease; a session_state follows. */
export interface SessionClaimed {
  kind: 'session_claimed';
  key: string;
}

/**
 * SessionMeta is what the history panel lists. Assembled from a
 * transcript's head and tail without reading the conversation in
 * between — a history list must not cost the sum of every transcript.
 */
export interface SessionMeta {
  session_id: string;
  agent?: string;
  connection?: string;
  /**
   * Catalog and LaunchModel are how the session was started (the model
   * as asked: a slot name or an id), for starting another the same way;
   * Model is what it actually ran, from its summary.
   */
  catalog?: string;
  launch_model?: string;
  model?: string;
  cwd?: string;
  dir?: string;
  title?: string;
  /**
   * UserTitle is the person's name for the session, when they gave one.
   * Title above is then the SAME string — the effective title, so every
   * reader shows the name without knowing where it came from — and this
   * field says it was theirs.
   */
  user_title?: string;
  /**
   * Parent is the session that launched this one: the orchestrator of
   * its workspace, or the member that spawned it. Empty for a session a
   * person started.
   */
  parent?: string;
  started_ms?: number;
  ended_ms?: number;
  end_reason?: string;
  events?: number;
  /**
   * Bytes is the transcript's size on disk, so the UI can say what
   * history costs and offer to prune the expensive ones.
   */
  bytes?: number;
  /**
   * Preview is a few recent human/agent lines taken from the same bounded
   * tail read used for the metadata. It gives the always-visible history
   * list enough context without loading or sending whole transcripts.
   */
  preview?: string;
  /**
   * Snippet is the line that matched, with a little either side. Absent
   * when the query matched metadata instead (the row already shows the
   * title and directory, so quoting them back is noise) or when there
   * was no query at all.
   */
  snippet?: string;
  /**
   * Live / Detached / RowKey are stamped on the way out from the
   * roster, not read from the file — the transcript index knows what a
   * session WAS, and only the roster knows what it is doing now.
   * 
   * The panel did not have these at all, so it would happily offer to
   * resume a session that was already running: the precise duplication
   * the menu's filter exists to prevent, in the view that had no
   * filter. Same predicate, both views (see rosterIndex).
   */
  live?: boolean;
  detached?: boolean;
  row_key?: string;
}

/**
 * SessionState is one Agent window's view: its own row and the questions
 * waiting on it.
 */
export interface SessionState {
  kind: 'session_state';
  key: string;
  state: State;
}

/**
 * SlotSpec is one slot as written: a model on an adapter. Effort and
 * Connection may be empty (the adapter's default effort; the adapter
 * direct).
 */
export interface SlotSpec {
  adapter: string;
  connection?: string;
  model?: string;
  effort?: string;
}

/**
 * SlotView is one slot of a curated catalog: a model on an adapter, with
 * its effort. Nothing about permissions (see catalogs.go).
 */
export interface SlotView {
  slot: string;
  adapter: string;
  connection?: string;
  model?: string;
  effort?: string;
  available: boolean;
  note?: string;
}

export interface State {
  version: number;
  rows: Row[] | null;
  /**
   * Asks are permission questions waiting for a human (§12). They ride
   * the roster's own push so the sidebar needs no second subscription.
   */
  asks?: Ask[];
  /**
   * Questions are question sets waiting for a human: an adapter's form
   * elicitation (Claude Code's AskUserQuestion) or a workspace member's
   * decision_request. The asker waits for the answer.
   */
  questions?: PendingQuestion[];
  /**
   * Recent is the remembered session history (§13) — what a reboot or a
   * closed window would otherwise have cost you.
   */
  recent?: Session[];
  /**
   * Adapters is which agents this box can actually launch over ACP
   * (docs/AGENT_APP.md §6). The launcher renders unavailable ones greyed
   * with their reason rather than hiding them, so "why can I not pick
   * Claude here" has an answer on screen.
   */
  adapters?: Adapter[];
  /**
   * Catalogs are what the launcher offers first (catalogs.go): each with
   * the availability of its slots, greyed with a reason like an adapter.
   */
  catalogs?: CatalogView[];
  /**
   * Keys are the connection keys the launcher can store: set or not, and
   * a stored key's last four characters. Never a value.
   */
  keys?: KeyView[];
  /**
   * Connections are the named ways to reach an adapter (built in, and
   * agents.json's), which a tier may name instead of the adapter direct.
   */
  connections?: ConnectionView[];
  /**
   * AdapterOptions is what each adapter last reported when a session of
   * it started: its version, approval presets and settings (models,
   * efforts). The Stacks tab and the launcher's Advanced and Permissions
   * controls offer these instead of free text; an adapter that has never
   * run here has no entry, and its fields are typed.
   */
  adapter_options?: AdapterOptions[];
  /**
   * Launch is the remembered permission default the launcher starts a
   * session with (agents.json `launch`).
   */
  launch: LaunchPrefs;
  /**
   * HasDefaultPrompt says whether a stored default prompt exists, so the
   * launcher can say that a new session will not start empty. Only the
   * FLAG rides the state push — the text itself is fetched on demand
   * (agent_default prompt), because a page of prose on every roster push
   * would reach every subscriber several times a second during a turn.
   */
  has_default_prompt?: boolean;
}

/**
 * Subscribe asks for the whole roster, now and on every change. Handled by
 * the SDK's StateService.
 */
export interface Subscribe {
  kind: 'subscribe';
}

/**
 * Supervisor tunes the watchdog that tells the orchestrator when work has
 * stalled (agentd workspace_supervisor.go). Empty fields take its defaults.
 */
export interface Supervisor {
  off?: boolean;
  /**
   * Quiet is how long a turn may go without a word, a tool or a busy
   * process before its member counts as wedged.
   */
  quiet?: string;
  /**
   * Idle is how long a member may sit idle with open work, or the whole
   * team idle with the plan unfinished, before the orchestrator hears.
   */
  idle?: string;
  /**
   * Repeat is the wait before the same finding is sent again; it
   * doubles each time.
   */
  repeat?: string;
  /**
   * MaxPrompts is how many times the same finding is sent before the
   * owner is told instead.
   */
  max_prompts?: number;
}

/**
 * TranscriptEvent is one new or changed event. An event with Append set is
 * a delta to the one with its Seq.
 */
export interface TranscriptEvent {
  kind: 'transcript_event';
  key: string;
  event: Event;
}

/**
 * TranscriptSnapshot is a session's history, sent in bounded frames: the
 * first has Reset (replace what you hold), the rest append.
 */
export interface TranscriptSnapshot {
  kind: 'transcript_snapshot';
  key: string;
  reset: boolean;
  events: Event[] | null;
}

/**
 * TranscriptSubscribe watches a session's transcript, and re-affirms the
 * watch: a watcher agentd has not heard from for its TTL is dropped, so a
 * frontend repeats this every agentclient.WatcherRefresh.
 */
export interface TranscriptSubscribe {
  kind: 'transcript_subscribe';
  key: string;
  /**
   * Replay asks for the whole history again even from a watcher agentd
   * already knows, after a frontend lost its copy (a reload, a missed
   * delta).
   */
  replay?: boolean;
}

/** Unsubscribe stops a Subscribe. */
export interface Unsubscribe {
  kind: 'unsubscribe';
}

export interface Usage {
  used: number;
  size: number;
}

/**
 * UsagePatch updates rows' context accounting (Row.Used, Row.Size),
 * coalesced to at most one send per 500ms.
 */
export interface UsagePatch {
  kind: 'usage_patch';
  rows: UsageRow[] | null;
}

/** UsageRow is one row's counters. */
export interface UsageRow {
  key: string;
  used: number;
  size: number;
}

export interface Workspace {
  /**
   * QAAuthors names the authors of threads read back from an earlier
   * workspace's files, who are not members of this one.
   */
  qa_authors?: Record<string, string>;
  /**
   * QADir is the directory holding one file per QA thread
   * (<thread>.md), written by Wash as threads change.
   */
  qa_dir?: string;
  qa: QAThread[] | null;
  /**
   * Approvals apply to every member of this workspace, whatever its cwd.
   * Members work in worktrees the orchestrator chooses, and those are as
   * often siblings of project_root as children of it, so a path-scoped
   * rule cannot cover a fleet. Membership is the scope instead: these
   * rules carry no Cwd, and agentpolicy's matcher is reused verbatim.
   */
  approvals?: Rule[];
  /**
   * Catalog is where members' models come from (a slot name in a
   * member's `model` resolves against it): the orchestrator's own catalog
   * at setup, changeable with workspace_configure.catalog for later
   * launches.
   */
  catalog?: string;
  id: string;
  name: string;
  project_root: string;
  orchestrator: string;
  state: string;
  revision: number;
  max_active: number;
  max_members: number;
  /** Plan is the workspace's node graph; PlanRevision counts its changes. */
  plan: Node[] | null;
  plan_revision: number;
  /** PlanFile is where Wash writes the plan as it changes (TOML). */
  plan_file?: string;
  /** Legend says what the orchestrator's emojis and states mean. */
  legend?: string;
  /**
   * Roles are instruction templates by member role, put before a new
   * member's own instructions (workspace.toml [roles.<role>]).
   */
  roles?: Record<string, string>;
  /**
   * ContextWarn is the share of its context window at which a member's
   * use is reported to the orchestrator, once; 0 is the default.
   */
  context_warn?: number;
  /** Supervisor tunes the stall watchdog. */
  supervisor?: Supervisor;
  /**
   * Digest holds the orchestrator's routine mail (progress, notes,
   * lifecycle) for this long, or until something that needs it arrives
   * (a result, a question, an answer, an owner's decision), and delivers
   * it in one turn. "" delivers as it comes. With twenty members every
   * progress report was a turn of the owner's own session (Redoubt, R11).
   */
  digest?: string;
  /** Nudged are the lifecycle nudges already sent, so each goes once. */
  nudged?: string[];
  members: Member[] | null;
  assignments: Assignment[] | null;
  messages: Message[] | null;
}

/** WorkspaceAction is a human's action in the workspace sidebar. */
export interface WorkspaceAction {
  kind: 'workspace_action';
  key: string;
  /**
   * Name is the operation: member_open | member_resume |
   * member_message | member_inspect.
   */
  name: string;
  arguments: WorkspaceActionArgs;
}

/**
 * WorkspaceActionArgs are an action's arguments; each operation reads its
 * own.
 */
export interface WorkspaceActionArgs {
  /**
   * MemberID names the member for member_open, member_resume and
   * member_inspect.
   */
  member_id?: string;
  /** Recipient is the member a member_message goes to. */
  recipient?: string;
  /** Body is a member_message's text. */
  body?: string;
}

/** WorkspaceApproval is a member's question waiting for the human. */
export interface WorkspaceApproval {
  id: string;
  member_id: string;
  tool: string;
  subject: string;
}

/**
 * WorkspacePatch changes a WorkspaceState: the frame fields and workspace
 * fields that changed (null removes one), and the plan's nodes by id. It
 * applies to the frame with sequence Base; a frontend holding another asks
 * for the whole frame again (workspace_refresh).
 */
export interface WorkspacePatch {
  kind: 'workspace_patch';
  key: string;
  base: number;
  sequence: number;
  /** Frame holds changed WorkspaceState fields by their JSON name. */
  frame: Record<string, unknown> | null;
  /** Workspace holds changed swarm.Workspace fields, except the plan. */
  workspace: Record<string, unknown> | null;
  plan?: WorkspacePlanPatch;
}

/**
 * WorkspacePlanPatch changes the plan: nodes replaced or added, ids
 * removed, and the new order when it changed.
 */
export interface WorkspacePlanPatch {
  upsert: Node[] | null;
  remove: string[] | null;
  order?: string[];
}

/** WorkspaceRefresh asks for the session's workspace frame again. */
export interface WorkspaceRefresh {
  kind: 'workspace_refresh';
  key: string;
}

/** WorkspaceResult answers a WorkspaceAction. */
export interface WorkspaceResult {
  kind: 'workspace_result';
  key: string;
  operation: string;
  error?: string;
  /** Transcript answers member_inspect. */
  transcript?: WorkspaceTranscript;
}

/**
 * WorkspaceState is the whole sidebar frame for an orchestrator's (or a
 * member's) Agent window. Sent in full on refresh and when a patch cannot
 * apply; otherwise changes arrive as WorkspacePatch.
 */
export interface WorkspaceState {
  kind: 'workspace_state';
  key: string;
  /** Sequence numbers this frame; a patch names the sequence it applies to. */
  sequence: number;
  /**
   * Workspace is the workspace this session belongs to, or null when it
   * belongs to none (the sidebar is then not shown).
   */
  workspace: Workspace | null;
  /** Preview is the transcript of the member the window has selected. */
  preview?: WorkspaceTranscript;
  /**
   * Activity and ActivityDetail are each member's live activity (by
   * member id): thinking, tool use, responding, waiting, …
   */
  activity?: Record<string, string>;
  activity_detail?: Record<string, string>;
  /** Usage is each member's context accounting, by member id. */
  usage?: Record<string, Usage>;
  /** Approvals are the members' questions waiting for the human. */
  approvals?: WorkspaceApproval[];
  /** Questions are the members' question sets waiting for the human. */
  questions?: PendingQuestion[];
  /** QAMarkdown is the QA document as it is written to disk. */
  qa_markdown?: string;
  qa_document_status?: QADocumentStatus;
  /** PlanFileStatus is where the plan file stands on disk. */
  plan_file_status?: QADocumentStatus;
}

/**
 * WorkspaceTranscript is a member's recent transcript: the selected
 * member's preview, or member_inspect's answer.
 */
export interface WorkspaceTranscript {
  member_id: string;
  events: Event[] | null;
  /** Asks are the member's questions waiting for the human, when it runs. */
  asks?: Ask[];
  /** Questions are the member's question sets waiting for the human. */
  questions?: PendingQuestion[];
  /**
   * Note says what the transcript is when it is not live: an ended
   * member's archive.
   */
  note?: string;
}

/** Every request, discriminated by kind. */
export type AgentdRequest =
  | AgentSetCatalog
  | AgentDeleteCatalog
  | AgentSetLaunch
  | ManagerSubscribe
  | SessionClaim
  | Focus
  | AgentHistory
  | AgentResume
  | AgentRename
  | AgentDelete
  | AgentPrune
  | AgentSetKey
  | AgentTestKey
  | Subscribe
  | Unsubscribe
  | AgentStart
  | AgentPrompt
  | AgentCancel
  | AgentDetach
  | AgentReattach
  | AgentStop
  | AgentSetYolo
  | AgentSetMode
  | AgentSetConfig
  | AgentAddRoot
  | AgentRemoveRoot
  | AgentQuestionAnswer
  | AgentAnswer
  | AgentDefaultPrompt
  | AgentSetDefaultPrompt
  | TranscriptSubscribe
  | WorkspaceRefresh
  | WorkspaceAction;
export type AgentdRequestKind = AgentdRequest['kind'];

/** Every push, discriminated by kind. */
export type AgentdPush =
  | CatalogSaved
  | SessionClaimed
  | ClaimDenied
  | Raise
  | Attach
  | History
  | HistoryDeleted
  | HistoryPruned
  | KeySaved
  | KeyTest
  | UsagePatch
  | PreviewPatch
  | RosterState
  | ManagerState
  | SessionState
  | AgentStarted
  | Detach
  | DefaultPrompt
  | TranscriptSnapshot
  | TranscriptEvent
  | WorkspaceState
  | WorkspacePatch
  | WorkspaceResult;
export type AgentdPushKind = AgentdPush['kind'];

/** Every event, discriminated by kind. */
export type DesktopEvent =
  | OpenSession
  | Notify;
export type DesktopEventKind = DesktopEvent['kind'];
