// Code generated by `make gen-agent-protocol` from internal/agentproto; DO NOT EDIT.
//
// The protocol between com.wash.agentd and its frontends (docs/AGENT_PROTOCOL.md).

/** The protocol version agentd sends on every State (agentproto.Version). */
export const AGENT_PROTOCOL_VERSION = 1;

/**
 * Adapter is one way to reach an agent over ACP, as the launcher shows it:
 * whether this box can start it, and if not, why.
 */
export interface Adapter {
  /** ID is what the launcher and the roster call this agent. */
  id: string;
  /** Name is what a human reads. */
  name: string;
  /** Note explains a greyed row: why this one cannot be used here. */
  note?: string;
  /** Available is whether it can be launched here. */
  available: boolean;
}

/** AgentAddRoot widens which folders a session may reach beyond its cwd. */
export interface AgentAddRoot {
  kind: 'agent_add_root';
  key: string;
  path: string;
}

/** AgentAnswer answers a question (Ask) by its id. */
export interface AgentAnswer {
  kind: 'agent_answer';
  id: string;
  /** Decision is allow | deny. */
  decision: string;
  /**
   * Remember writes Rule (or the ask's suggested rule) to the policy, so
   * the question is not asked again.
   */
  remember: boolean;
  rule: string;
  /**
   * Scope picks the table a remembered answer is written to: "" (or
   * anything unrecognised) is the global one, "workspace" is the asking
   * member's workspace's. An unknown value must not silently widen
   * anything, so it falls back to the narrower, global behaviour.
   */
  scope?: string;
}

/**
 * AgentCancel ends the running turn; the agent answers with a cancelled
 * stop.
 */
export interface AgentCancel {
  kind: 'agent_cancel';
  key: string;
}

/** AgentDefaultPrompt asks for the stored default prompt's text. */
export interface AgentDefaultPrompt {
  kind: 'agent_default_prompt';
}

/** AgentDelete deletes a stored session that is not running. */
export interface AgentDelete {
  kind: 'agent_delete';
  session_id: string;
}

/**
 * AgentDetach leaves a session running with no window: its roster row
 * stays and offers Reattach, and its controller window is told to close.
 */
export interface AgentDetach {
  kind: 'agent_detach';
  key: string;
}

/**
 * AgentHistory searches the stored sessions: their metadata and, with a
 * query, their conversations.
 */
export interface AgentHistory {
  kind: 'agent_history';
  query?: string;
  /** Limit bounds the answer; 0 and anything above 200 mean 200. */
  limit?: number;
}

/** AgentProfile describes launch settings and an optional enforced capability profile. */
export interface AgentProfile {
  capability?: string;
  /**
   * Approval "auto" launches the member with host auto-approval on; ""
   * and "ask" leave every unmatched tool call to the human.
   */
  approval?: string;
  provider: string;
  /**
   * Connection names how the provider is reached ("opencode@openrouter");
   * empty is the provider direct. agentd owns the list and checks it.
   */
  connection?: string;
  model?: string;
  thinking?: string;
  configs?: Record<string, string>;
  /**
   * Subagents "deny" removes the provider's own subagent tool, so the
   * member's work stays in its transcript and the workspace's accounting.
   * "" and "allow" leave it available.
   */
  subagents?: string;
}

/**
 * AgentPrompt is another turn on a live session. Sent while a turn runs,
 * it is queued and sent when the turn ends.
 */
export interface AgentPrompt {
  kind: 'agent_prompt';
  key: string;
  text?: string;
  /**
   * Blocks are attachments sent with the text: a pasted image, a file
   * the composer's Attach button picked. Kept as a wash-shaped struct
   * rather than acp.ContentBlock so the app→service wire is ours to
   * validate — the router carries this from a window, and a window is
   * not trusted to name a mime type or a path.
   */
  blocks?: PromptAttachment[];
}

/** AgentPrune deletes stored sessions older than MaxAgeMS. */
export interface AgentPrune {
  kind: 'agent_prune';
  /**
   * MaxAgeMS is how old a session must be to go; 0 means every stored
   * session that is not running. A duration rather than a cutoff so a
   * browser clock on another machine cannot be the one deciding.
   */
  max_age_ms: number;
}

/** AgentReattach opens a window onto a running session. */
export interface AgentReattach {
  kind: 'agent_reattach';
  key: string;
}

/** AgentRemoveRoot narrows it again. */
export interface AgentRemoveRoot {
  kind: 'agent_remove_root';
  key: string;
  path: string;
}

/**
 * AgentRename names a session, by roster key when it is running or by
 * session id when it is not. An empty title clears the person's name and
 * the agent's own shows again.
 */
export interface AgentRename {
  kind: 'agent_rename';
  key?: string;
  session_id?: string;
  title: string;
}

/**
 * AgentResume reopens a stored session: session/load replays it, and an
 * Agent window opens on it (or the one already showing it comes forward).
 */
export interface AgentResume {
  kind: 'agent_resume';
  session_id: string;
}

/**
 * AgentSetConfig changes one of the agent's own settings (Row.Configs):
 * model, reasoning effort, plan mode, …
 */
export interface AgentSetConfig {
  kind: 'agent_set_config';
  key: string;
  id: string;
  value: string;
}

/**
 * AgentSetDefaultPrompt stores the default prompt. Empty text is a
 * deletion, not a validation failure.
 */
export interface AgentSetDefaultPrompt {
  kind: 'agent_set_default_prompt';
  text: string;
}

/**
 * AgentSetKey stores a connection key (State.Keys), or clears it with an
 * empty value. The value is never sent back.
 */
export interface AgentSetKey {
  kind: 'agent_set_key';
  name: string;
  value?: string;
}

/** AgentSetMode switches the agent's approval preset (Row.Modes). */
export interface AgentSetMode {
  kind: 'agent_set_mode';
  key: string;
  mode: string;
}

/** AgentSetYolo turns host-side auto-approval on or off for one session. */
export interface AgentSetYolo {
  kind: 'agent_set_yolo';
  key: string;
  on: boolean;
}

/** AgentStart starts a session. */
export interface AgentStart {
  kind: 'agent_start';
  /**
   * Stack and Tier choose the settings (stacks.go); Tier defaults to
   * frontier. Agent and Model are the launcher's Advanced overrides, and
   * Agent alone, with no stack, is how `wash ai --agent` starts.
   */
  stack?: string;
  tier?: string;
  agent?: string;
  model?: string;
  /** Cwd is the folder the session works in; empty is the home folder. */
  cwd: string;
  /** Prompt is sent as the first turn, after the stored default prompt. */
  prompt?: string;
  /**
   * Open asks agentd to open (or focus) an Agent window on the new
   * session, for a starter that is not itself that window (the manager).
   */
  open?: boolean;
  /**
   * Claim makes the starter the session's controller (see Roles): an
   * Agent window starting the session it will show.
   */
  claim?: boolean;
  /**
   * ReqID is opaque to agentd and echoed back on agent_started, success
   * or failure. A host with ONE session per process (wash-ai) never needs
   * it — the reply can only be about the one thing it asked for. A host
   * with several (wash-edit's agent tabs) cannot tell two concurrent
   * starts apart without it, and a FAILED start carries no key at all, so
   * there would be nothing to attribute the error to.
   */
  req_id?: string;
}

/** AgentStarted answers AgentStart: the new session's key, or why it failed. */
export interface AgentStarted {
  kind: 'agent_started';
  key?: string;
  session_id?: string;
  req_id?: string;
  error?: string;
}

/** AgentStop ends a session and its adapter. */
export interface AgentStop {
  kind: 'agent_stop';
  key: string;
}

/**
 * AgentTestKey checks a key against its provider: the typed value, or the
 * stored one when Value is empty.
 */
export interface AgentTestKey {
  kind: 'agent_test_key';
  name: string;
  value?: string;
}

/**
 * Ask is one question waiting for a human. It rides the roster's own
 * state push, so the sidebar needs no second subscription.
 */
export interface Ask {
  /** ID is agentd's handle for this question; the answer names it. */
  id: string;
  /**
   * Agent / Tool / Subject are what the human reads: "claude wants to
   * run `git push origin main`".
   */
  agent: string;
  tool: string;
  subject?: string;
  cwd?: string;
  dir?: string;
  /**
   * SuggestedRule is what "Always allow" would write. Shown ON the
   * button — what you clicked is what gets saved.
   */
  suggested_rule?: string;
  /**
   * RuleCwd is the directory that rule would be confined to, when it
   * would be (agentpolicy.RuleScope): a Bash rule from one project must
   * not buy the same command in every other checkout.
   */
  rule_cwd?: string;
  /**
   * RowKey ties the question to its roster row (same "<instance>:<chan>"
   * key for terminals; hosted sessions mint their own), so the sidebar
   * can render it against the right agent.
   */
  row_key: string;
  /**
   * WorkspaceName is set when the asking session is a workspace member,
   * and is what lets the prompt offer "always, for this workspace"
   * alongside the global "always". The ID is deliberately NOT sent: the
   * answer names a scope, never a target (see the answer path).
   */
  workspace_name?: string;
  /** AgeMS is how long it has been waiting, as of the push. */
  age_ms: number;
}

export interface Assignment {
  id: string;
  assigner: string;
  member_id: string;
  text: string;
  state: string;
  result?: string;
}

/**
 * Attach hands a window agentd opened the session it is to show; the lease
 * is already its.
 */
export interface Attach {
  kind: 'attach';
  key: string;
}

/**
 * ClaimDenied refuses the lease: another instance holds it, and has been
 * raised. A window denied its session closes.
 */
export interface ClaimDenied {
  kind: 'claim_denied';
  key: string;
}

/** Command is one slash command the agent offers. */
export interface Command {
  name: string;
  description?: string;
}

/** Config is one agent setting the session can change. */
export interface Config {
  id: string;
  name: string;
  description?: string;
  current?: string;
  values?: ConfigValue[];
}

export interface ConfigValue {
  value: string;
  name: string;
  description?: string;
}

/** DefaultPrompt is the stored default prompt's text, answering either. */
export interface DefaultPrompt {
  kind: 'default_prompt';
  text: string;
}

/**
 * Detach tells a session's controller window that the session was
 * detached elsewhere (the rail, the manager), so it closes.
 */
export interface Detach {
  kind: 'detach';
  key: string;
}

export interface Document {
  path: string;
  title: string;
}

/**
 * Event is one line in a transcript.
 * 
 * Flat and string-typed on purpose: this crosses the router to the FE, and
 * structured byte fields get base64'd on the way (the CBOR pitfall).
 */
export interface Event {
  seq: number;
  /**
   * Kind is one of the Event* kinds above: message | thought | tool |
   * decision | user | terminal | image | collaboration.
   */
  kind: string;
  /** Text is the message body, accumulated across streamed chunks. */
  text?: string;
  /** Tool fields, set when Kind == EventTool. */
  tool_id?: string;
  tool_kind?: string;
  title?: string;
  status?: string;
  /**
   * Path is the file a tool call touched (its first ACP location, or
   * the diff's), so a host can open it. Diff is the unified diff of what
   * the call changed, rendered once here from the agent's before/after
   * pair (diff.go). Both on EventTool only.
   */
  path?: string;
  diff?: string;
  /** Mime is set on EventImage; Text then holds the base64 bytes. */
  mime?: string;
  /** Reason and Detail are set on EventDecision. */
  reason?: string;
  detail?: string;
  /** Channel is set on EventTerminal: the raw channel id to render. */
  channel?: number;
  /** AtMS is wall-clock at first append, for the FE's own clock anchoring. */
  at_ms: number;
  /**
   * Append marks a wire-only delta: Text is what was ADDED to the event
   * with this Seq since the last emit, not the whole message. Never set
   * on a stored or snapshotted event (transcript_emit.go).
   */
  append?: boolean;
  /**
   * TextLen is the message's byte length after this event applies, on
   * message/thought events. A consumer applying a delta checks its own
   * length + the delta against it, and asks for a replay on mismatch.
   */
  text_len?: number;
}

/**
 * Focus asks for a session's window to come forward, opening one if
 * nothing is showing it. The shell sends it when a notification about the
 * session is clicked; frontends send it to go to a running session.
 */
export interface Focus {
  kind: 'wash.focus';
  key: string;
}

/**
 * History answers AgentHistory, newest first, each session stamped with
 * what the roster says about it now.
 */
export interface History {
  kind: 'history';
  query: string;
  sessions: SessionMeta[] | null;
}

/** HistoryDeleted answers AgentDelete. */
export interface HistoryDeleted {
  kind: 'history_deleted';
  session_id: string;
  error?: string;
}

/** HistoryPruned answers AgentPrune: how many sessions went. */
export interface HistoryPruned {
  kind: 'history_pruned';
  deleted: number;
}

export interface Item {
  id: string;
  text: string;
  emoji?: string;
  state: string;
  revision: number;
}

/** KeySaved answers AgentSetKey. */
export interface KeySaved {
  kind: 'key_saved';
  name: string;
  error?: string;
}

/** KeyTest answers AgentTestKey with what the provider said. */
export interface KeyTest {
  kind: 'key_test';
  name: string;
  ok: boolean;
  detail: string;
}

/** KeyView is a key as the launcher shows it. */
export interface KeyView {
  id: string;
  name: string;
  set: boolean;
  /** Hint is the stored key's last four characters. */
  hint?: string;
  testable?: boolean;
}

/**
 * ManagerState is the Agents manager's view of the roster: every row with
 * its transcript preview and workspace placement, without the per-session
 * settings only a controller needs.
 */
export interface ManagerState {
  kind: 'manager_state';
  state: State;
}

/**
 * ManagerSubscribe registers the sender as a manager and asks for the
 * manager's roster view, now and on every change.
 */
export interface ManagerSubscribe {
  kind: 'manager_subscribe';
}

export interface Member {
  key?: string;
  package?: string;
  role?: string;
  instructions?: string;
  initial_task?: string;
  usage?: Usage;
  profile?: string;
  /**
   * Tier is the stack tier the member was launched from, resolved into
   * LaunchSettings at reservation like a profile.
   */
  tier?: string;
  launch_settings?: AgentProfile;
  initial_configs?: Record<string, string>;
  /**
   * Adjusted are settings the orchestrator changed on the live member
   * (member_control configure), applied over LaunchSettings on every
   * resume. Kept apart so the keyed launch definition stays as declared.
   */
  adjusted_configs?: Record<string, string>;
  /**
   * AutoApprove is whether host auto-approval is on for this member now:
   * set from Approval at launch, and by the human's toggle afterwards.
   * Kept here, not on the session, so a restart (which pauses rather
   * than ends a member) does not silently switch it off; it ends with
   * the workspace, never outliving the job it was granted for.
   */
  auto_approve?: boolean;
  id: string;
  name: string;
  provider: string;
  cwd: string;
  session_id: string;
  creator: string;
  lifetime: string;
  state: string;
  status?: string;
  emoji?: string;
  waiting?: string;
  waiting_for?: string;
  /**
   * WaitingOn is a set of assignments this member created and is waiting
   * for as a whole: their results are held and delivered together in one
   * turn once every one has completed or failed. One wake-up per review
   * round instead of one per reviewer.
   */
  waiting_on?: string[];
  status_updated_at?: number;
  can_spawn: boolean;
  retire?: boolean;
}

export interface Message {
  thread_id?: string;
  id: string;
  swarm_id: string;
  sender: string;
  recipient: string;
  type: string;
  body: string;
  reply_to?: string;
  assignment_id?: string;
  request_id?: string;
  delivery: string;
  created_at: number;
}

/** Mode is one approval/sandbox preset an agent offers. */
export interface Mode {
  id: string;
  name: string;
  description?: string;
}

/** Package is the human-facing description of a package code. */
export interface Package {
  title: string;
}

/**
 * PreviewPatch updates rows' transcript previews (Row.Preview) in the
 * manager's view.
 */
export interface PreviewPatch {
  kind: 'preview_patch';
  rows: PreviewRow[] | null;
}

/** PreviewRow is one row's preview. */
export interface PreviewRow {
  key: string;
  preview?: string;
}

/**
 * PromptAttachment is one attachment on its way to an ACP content block.
 * Type is "image" or "file"; anything else is dropped.
 */
export interface PromptAttachment {
  type: string;
  /** Image: base64 bytes and their mime type. */
  mime?: string;
  data?: string;
  /**
   * File: an absolute path, confined against the session cwd before it
   * becomes a resource_link.
   */
  path?: string;
  name?: string;
}

/** QADocumentStatus is where the workspace's QA file stands on disk. */
export interface QADocumentStatus {
  path: string;
  /** State is unconfigured | pending | saved | error. */
  state: string;
  error?: string;
  updated_at?: number;
}

export interface QAEvent {
  id: string;
  author: string;
  kind: string;
  body: string;
  message_id?: string;
  created_at: number;
}

export interface QAThread {
  id: string;
  package: string;
  title: string;
  creator: string;
  assignee: string;
  state: string;
  blocking: boolean;
  revision: number;
  decision_refs: string[] | null;
  evidence?: string;
  events: QAEvent[] | null;
}

/** Raise tells a session's controller to come forward. */
export interface Raise {
  kind: 'wash.focus';
  key: string;
}

/**
 * RosterState is the whole roster, sent by the StateService to every
 * subscriber on each change.
 */
export interface RosterState {
  kind: 'state';
  state: State;
}

/** Row is one hosted agent session. */
export interface Row {
  /**
   * Key identifies the session on the roster: "acp:<n>", minted by
   * agentd. Every session-scoped message names it.
   */
  key: string;
  /** Agent is the slug ("claude", "codex", …). */
  agent: string;
  /**
   * State is running | working | needs-input | done | failed, or
   * "stale" once an exited session's row is ageing out.
   */
  state: string;
  /**
   * Reason qualifies the state: which input is wanted (permission |
   * idle), or how a turn or session ended (cancelled, error, exited, …).
   */
  reason?: string;
  /**
   * SessionID is the agent's own session id — what makes a row
   * actionable later (`--resume`, copy-session-id).
   */
  session_id?: string;
  /**
   * Cwd is where the agent is working; Dir is its basename, which is
   * what a 300px sidebar column can actually show.
   */
  cwd?: string;
  dir?: string;
  /**
   * Branch / Dirty come from agentd shelling git in Cwd, lazily and
   * cached — never from the agent's hooks (§7).
   */
  branch?: string;
  dirty?: boolean;
  /**
   * SinceMS is how long the row has been in this state, as of the push.
   * The FE anchors its own clock to it (no cross-clock comparison).
   */
  since_ms: number;
  /**
   * Used / Size are the agent's context accounting (usage_update), and
   * Title is its own name for the session (session_info_update).
   */
  used?: number;
  size?: number;
  title?: string;
  /**
   * Preview is populated only in the compact manager projection. Live
   * transcript changes arrive as bounded Bulk patches, never by
   * republishing the complete roster.
   */
  preview?: string;
  /**
   * Mode is the agent's active approval preset and Modes what it offers
   * (docs/AGENT_APP.md §9). Empty for an agent with no such notion.
   */
  mode?: string;
  modes?: Mode[];
  /**
   * Yolo is wash answering this session's permission questions with
   * "allow" instead of asking. Host-side and per-session; it is on the
   * row so every surface that shows the session can SAY so — an
   * auto-approving agent that looks like any other is the failure mode
   * this flag exists to prevent.
   */
  yolo?: boolean;
  /**
   * Configs is the agent's generic settings block (model, reasoning
   * effort, plan mode…). Commands are its own slash commands.
   */
  configs?: Config[];
  commands?: Command[];
  /**
   * Detached marks a session still running with no window pointing at
   * it — the sidebar offers Reattach rather than focus.
   */
  detached?: boolean;
  /**
   * Queued is how many prompts are waiting for the current turn to end
   * (docs/AGENT_MESSENGER.md semantics: a message typed mid-reply is
   * sent when the reply finishes, not dropped and not interleaved).
   */
  queued?: number;
  /**
   * Roots are folders this session may reach BEYOND its cwd (roots.go).
   * On the row because every surface that shows a session must be able
   * to say how wide it is: a session with three extra roots is a
   * different thing from one confined to its own folder, and only the
   * person who widened it would otherwise know.
   */
  roots?: string[];
  /**
   * Stale marks the row of a session that is no longer hosted: shown
   * greyed, then dropped.
   */
  stale?: boolean;
  /**
   * Workspace places the session in a workspace team, so the Agents
   * window lists members under the orchestrator that leads them. Set
   * only on the manager's projection.
   */
  workspace?: RowWorkspace;
}

/** RowWorkspace is one session's place in a workspace team. */
export interface RowWorkspace {
  id: string;
  name: string;
  /**
   * LeadSession is the orchestrator's session: a member row nests under
   * the row with this session_id.
   */
  lead_session: string;
  orchestrator?: boolean;
  member: string;
  role?: string;
  package?: string;
  package_title?: string;
}

/** Rule is one line of the table. */
export interface Rule {
  /** Match is `Tool` or `Tool(pattern)`. */
  match: string;
  /** Decision is allow | deny | ask. */
  decision: string;
  /** Cwd scopes the rule to requests at or under this directory. */
  cwd?: string;
}

/** Session is one remembered agent session. */
export interface Session {
  session_id: string;
  agent: string;
  /**
   * Connection is what a resume must launch through again; Stack and
   * Tier are what the launcher defaults to next time (launchRecord).
   */
  connection?: string;
  stack?: string;
  tier?: string;
  cwd?: string;
  dir?: string;
  /**
   * Title is what this session was ABOUT, in the agent's own words —
   * it names its sessions on session_info_update once it works out what
   * the work is. "codex · mick" tells you nothing a week later; "Fix
   * the reconnect banner race" does.
   */
  title?: string;
  /**
   * UserTitle is the name a PERSON gave the session (session_admin.go).
   * When set it is what publishHistory puts in Title; the agent's own
   * title stays here underneath so clearing the user's falls back to it.
   */
  user_title?: string;
  /**
   * LastSeen is unix seconds — an absolute the FE renders as "2h ago",
   * and the only field a keepalive touches.
   */
  last_seen: number;
  /**
   * Live is set on the way out to the FE: a session whose agent is
   * running right now is in the roster above, so the Recent list greys
   * it rather than offering to resume what is already here.
   */
  live?: boolean;
  /**
   * Detached is a live session with no window pointing at it.
   * 
   * Live and REACHABLE are not the same thing, and treating them as one
   * is what made the History menu useless in exactly the case you open
   * it for. agent_detach sets the flag and closes the window but never
   * retires the row, so a detached session is still "live" — and the
   * menu, which hides live sessions to avoid offering to duplicate a
   * running one, hid the one thing you were trying to get back.
   * 
   * A detached session is not something to resume. It is something to
   * reattach to, which is a different verb with a different outcome.
   */
  detached?: boolean;
  /**
   * RowKey is the roster key this session is running as, present only
   * while it has a row. Reattach is key-addressed, not session-id
   * addressed, so the menu needs this to offer the verb at all.
   */
  row_key?: string;
}

/** SessionClaim takes (or re-affirms) the controller lease on a session. */
export interface SessionClaim {
  kind: 'session_claim';
  key: string;
}

/** SessionClaimed grants the lease; a session_state follows. */
export interface SessionClaimed {
  kind: 'session_claimed';
  key: string;
}

/**
 * SessionMeta is what the history panel lists. Assembled from a
 * transcript's head and tail without reading the conversation in
 * between — a history list must not cost the sum of every transcript.
 */
export interface SessionMeta {
  session_id: string;
  agent?: string;
  connection?: string;
  stack?: string;
  tier?: string;
  model?: string;
  cwd?: string;
  dir?: string;
  title?: string;
  /**
   * UserTitle is the person's name for the session, when they gave one.
   * Title above is then the SAME string — the effective title, so every
   * reader shows the name without knowing where it came from — and this
   * field says it was theirs.
   */
  user_title?: string;
  started_ms?: number;
  ended_ms?: number;
  end_reason?: string;
  events?: number;
  /**
   * Bytes is the transcript's size on disk, so the UI can say what
   * history costs and offer to prune the expensive ones.
   */
  bytes?: number;
  /**
   * Preview is a few recent human/agent lines taken from the same bounded
   * tail read used for the metadata. It gives the always-visible history
   * list enough context without loading or sending whole transcripts.
   */
  preview?: string;
  /**
   * Snippet is the line that matched, with a little either side. Absent
   * when the query matched metadata instead (the row already shows the
   * title and directory, so quoting them back is noise) or when there
   * was no query at all.
   */
  snippet?: string;
  /**
   * Live / Detached / RowKey are stamped on the way out from the
   * roster, not read from the file — the transcript index knows what a
   * session WAS, and only the roster knows what it is doing now.
   * 
   * The panel did not have these at all, so it would happily offer to
   * resume a session that was already running: the precise duplication
   * the menu's filter exists to prevent, in the view that had no
   * filter. Same predicate, both views (see rosterIndex).
   */
  live?: boolean;
  detached?: boolean;
  row_key?: string;
}

/**
 * SessionState is one Agent window's view: its own row and the questions
 * waiting on it.
 */
export interface SessionState {
  kind: 'session_state';
  key: string;
  state: State;
}

/** StackView is a stack as the launcher shows it. */
export interface StackView {
  id: string;
  name: string;
  /** Available is every tier startable here; Note says why not. */
  available: boolean;
  note?: string;
  tiers?: TierView[];
}

export interface State {
  version: number;
  rows: Row[] | null;
  /**
   * Asks are permission questions waiting for a human (§12). They ride
   * the roster's own push so the sidebar needs no second subscription.
   */
  asks?: Ask[];
  /**
   * Recent is the remembered session history (§13) — what a reboot or a
   * closed window would otherwise have cost you.
   */
  recent?: Session[];
  /**
   * Adapters is which agents this box can actually launch over ACP
   * (docs/AGENT_APP.md §6). The launcher renders unavailable ones greyed
   * with their reason rather than hiding them, so "why can I not pick
   * Claude here" has an answer on screen.
   */
  adapters?: Adapter[];
  /**
   * Stacks are what the launcher offers first (stacks.go): each with the
   * availability of its tiers, greyed with a reason like an adapter.
   */
  stacks?: StackView[];
  /**
   * Keys are the connection keys the launcher can store: set or not, and
   * a stored key's last four characters. Never a value.
   */
  keys?: KeyView[];
  /**
   * HasDefaultPrompt says whether a stored default prompt exists, so the
   * launcher can say that a new session will not start empty. Only the
   * FLAG rides the state push — the text itself is fetched on demand
   * (agent_default prompt), because a page of prose on every roster push
   * would reach every subscriber several times a second during a turn.
   */
  has_default_prompt?: boolean;
}

/**
 * Subscribe asks for the whole roster, now and on every change. Handled by
 * the SDK's StateService.
 */
export interface Subscribe {
  kind: 'subscribe';
}

/** TierView is one tier as the launcher shows it. */
export interface TierView {
  tier: string;
  adapter: string;
  connection?: string;
  model?: string;
  thinking?: string;
  capability?: string;
  /**
   * ReadOnly is set on the review tier: "enforced" where the adapter's
   * tools are restricted (Claude Code's reviewer capability), otherwise
   * "instruction" — the reviewer is asked not to write, and could.
   */
  read_only?: string;
  available: boolean;
  note?: string;
}

/**
 * TranscriptEvent is one new or changed event. An event with Append set is
 * a delta to the one with its Seq.
 */
export interface TranscriptEvent {
  kind: 'transcript_event';
  key: string;
  event: Event;
}

/**
 * TranscriptSnapshot is a session's history, sent in bounded frames: the
 * first has Reset (replace what you hold), the rest append.
 */
export interface TranscriptSnapshot {
  kind: 'transcript_snapshot';
  key: string;
  reset: boolean;
  events: Event[] | null;
}

/**
 * TranscriptSubscribe watches a session's transcript, and re-affirms the
 * watch: a watcher agentd has not heard from for its TTL is dropped, so a
 * frontend repeats this every agentclient.WatcherRefresh.
 */
export interface TranscriptSubscribe {
  kind: 'transcript_subscribe';
  key: string;
  /**
   * Replay asks for the whole history again even from a watcher agentd
   * already knows, after a frontend lost its copy (a reload, a missed
   * delta).
   */
  replay?: boolean;
}

/** Unsubscribe stops a Subscribe. */
export interface Unsubscribe {
  kind: 'unsubscribe';
}

export interface Usage {
  used: number;
  size: number;
}

/**
 * UsagePatch updates rows' context accounting (Row.Used, Row.Size),
 * coalesced to at most one send per 500ms.
 */
export interface UsagePatch {
  kind: 'usage_patch';
  rows: UsageRow[] | null;
}

/** UsageRow is one row's counters. */
export interface UsageRow {
  key: string;
  used: number;
  size: number;
}

export interface Workspace {
  qa_original_hash?: string;
  qa_document_id?: string;
  qa_preamble?: string;
  qa_authors?: Record<string, string>;
  qa_document?: Document;
  qa: QAThread[] | null;
  /**
   * Approvals apply to every member of this workspace, whatever its cwd.
   * Members work in worktrees the orchestrator chooses, and those are as
   * often siblings of project_root as children of it, so a path-scoped
   * rule cannot cover a fleet. Membership is the scope instead: these
   * rules carry no Cwd, and agentpolicy's matcher is reused verbatim.
   */
  approvals?: Rule[];
  /**
   * Packages names each package code ("CT1") for people: the sidebar groups
   * members and questions under "CT1 · Console input-flood test" instead of
   * a bare code, and member names can shrink to their role.
   */
  packages?: Record<string, Package>;
  profiles: Record<string, AgentProfile> | null;
  default_profile: string;
  /**
   * Stack is where members' tiers come from: set from the orchestrator's
   * own stack at setup, changeable with workspace_configure.stack.
   */
  stack?: string;
  id: string;
  name: string;
  project_root: string;
  orchestrator: string;
  state: string;
  revision: number;
  plan_revision: number;
  max_active: number;
  max_members: number;
  items: Item[] | null;
  document?: Document;
  members: Member[] | null;
  assignments: Assignment[] | null;
  messages: Message[] | null;
}

/** WorkspaceAction is a human's action in the workspace sidebar. */
export interface WorkspaceAction {
  kind: 'workspace_action';
  key: string;
  /**
   * Name is the operation: decision_response | member_open |
   * member_resume | member_message | member_inspect.
   */
  name: string;
  arguments: unknown;
}

/** WorkspaceApproval is a member's question waiting for the human. */
export interface WorkspaceApproval {
  id: string;
  member_id: string;
  tool: string;
  subject: string;
}

/**
 * WorkspaceItemsPatch changes the plan: items replaced or added, ids
 * removed, and the new order when it changed.
 */
export interface WorkspaceItemsPatch {
  upsert: Item[] | null;
  remove: string[] | null;
  order?: string[];
}

/**
 * WorkspacePatch changes a WorkspaceState: the frame fields and workspace
 * fields that changed (null removes one), and the plan items by id. It
 * applies to the frame with sequence Base; a frontend holding another asks
 * for the whole frame again (workspace_refresh).
 */
export interface WorkspacePatch {
  kind: 'workspace_patch';
  key: string;
  base: number;
  sequence: number;
  /** Frame holds changed WorkspaceState fields by their JSON name. */
  frame: Record<string, unknown> | null;
  /** Workspace holds changed swarm.Workspace fields, except items. */
  workspace: Record<string, unknown> | null;
  items?: WorkspaceItemsPatch;
}

/** WorkspaceRefresh asks for the session's workspace frame again. */
export interface WorkspaceRefresh {
  kind: 'workspace_refresh';
  key: string;
}

/** WorkspaceResult answers a WorkspaceAction. */
export interface WorkspaceResult {
  kind: 'workspace_result';
  key: string;
  operation: string;
  error?: string;
  /** Transcript answers member_inspect. */
  transcript?: WorkspaceTranscript;
}

/**
 * WorkspaceState is the whole sidebar frame for an orchestrator's (or a
 * member's) Agent window. Sent in full on refresh and when a patch cannot
 * apply; otherwise changes arrive as WorkspacePatch.
 */
export interface WorkspaceState {
  kind: 'workspace_state';
  key: string;
  /** Sequence numbers this frame; a patch names the sequence it applies to. */
  sequence: number;
  /**
   * Workspace is the workspace this session belongs to, or null when it
   * belongs to none (the sidebar is then not shown).
   */
  workspace: Workspace | null;
  /** Preview is the transcript of the member the window has selected. */
  preview?: WorkspaceTranscript;
  /**
   * Activity and ActivityDetail are each member's live activity (by
   * member id): thinking, tool use, responding, waiting, …
   */
  activity?: Record<string, string>;
  activity_detail?: Record<string, string>;
  /** Usage is each member's context accounting, by member id. */
  usage?: Record<string, Usage>;
  /** Approvals are the members' questions waiting for the human. */
  approvals?: WorkspaceApproval[];
  /** QAMarkdown is the QA document as it is written to disk. */
  qa_markdown?: string;
  qa_document_status?: QADocumentStatus;
  /**
   * DocumentText is the registered plan document's text, or
   * DocumentError why it could not be read.
   */
  document_text?: string;
  document_error?: string;
}

/**
 * WorkspaceTranscript is a member's recent transcript: the selected
 * member's preview, or member_inspect's answer.
 */
export interface WorkspaceTranscript {
  member_id: string;
  events: Event[] | null;
  /** Asks are the member's questions waiting for the human, when it runs. */
  asks?: Ask[];
  /**
   * Note says what the transcript is when it is not live: an ended
   * member's archive.
   */
  note?: string;
}

/** Every request, discriminated by kind. */
export type AgentdRequest =
  | ManagerSubscribe
  | SessionClaim
  | Focus
  | AgentHistory
  | AgentResume
  | AgentRename
  | AgentDelete
  | AgentPrune
  | AgentSetKey
  | AgentTestKey
  | Subscribe
  | Unsubscribe
  | AgentStart
  | AgentPrompt
  | AgentCancel
  | AgentDetach
  | AgentReattach
  | AgentStop
  | AgentSetYolo
  | AgentSetMode
  | AgentSetConfig
  | AgentAddRoot
  | AgentRemoveRoot
  | AgentAnswer
  | AgentDefaultPrompt
  | AgentSetDefaultPrompt
  | TranscriptSubscribe
  | WorkspaceRefresh
  | WorkspaceAction;
export type AgentdRequestKind = AgentdRequest['kind'];

/** Every push, discriminated by kind. */
export type AgentdPush =
  | SessionClaimed
  | ClaimDenied
  | Raise
  | Attach
  | History
  | HistoryDeleted
  | HistoryPruned
  | KeySaved
  | KeyTest
  | UsagePatch
  | PreviewPatch
  | RosterState
  | ManagerState
  | SessionState
  | AgentStarted
  | Detach
  | DefaultPrompt
  | TranscriptSnapshot
  | TranscriptEvent
  | WorkspaceState
  | WorkspacePatch
  | WorkspaceResult;
export type AgentdPushKind = AgentdPush['kind'];
